// One Long Impersonation -- Chapter 02: The Wait
// Survival analysis data -- generated by pipeline
// Model: Cox Proportional Hazards
// N = 256 inducted Performer artists

window.WAIT_DATA = {
  "cox_model": {
    "hazard_ratios": {
      "is_black": {
        "coef": 0.0792,
        "hr": 1.0824,
        "hr_lower": 0.6082,
        "hr_upper": 1.9263,
        "p_value": 0.787762,
        "significant": false
      },
      "is_female": {
        "coef": -0.411,
        "hr": 0.663,
        "hr_lower": 0.4148,
        "hr_upper": 1.0599,
        "p_value": 0.085972,
        "significant": false
      },
      "is_group": {
        "coef": -0.1525,
        "hr": 0.8585,
        "hr_lower": 0.6323,
        "hr_upper": 1.1656,
        "p_value": 0.328244,
        "significant": false
      },
      "genre_Blues/Early": {
        "coef": -0.9454,
        "hr": 0.3885,
        "hr_lower": 0.1866,
        "hr_upper": 0.8091,
        "p_value": 0.011534,
        "significant": true
      },
      "genre_Folk/Country": {
        "coef": -0.9842,
        "hr": 0.3737,
        "hr_lower": 0.1808,
        "hr_upper": 0.7724,
        "p_value": 0.007874,
        "significant": true
      },
      "genre_Heavy Metal": {
        "coef": -0.6255,
        "hr": 0.535,
        "hr_lower": 0.2169,
        "hr_upper": 1.3197,
        "p_value": 0.174521,
        "significant": false
      },
      "genre_Hip-Hop": {
        "coef": 0.953,
        "hr": 2.5934,
        "hr_lower": 1.1471,
        "hr_upper": 5.8633,
        "p_value": 0.022043,
        "significant": true
      },
      "genre_Pop": {
        "coef": -0.5287,
        "hr": 0.5894,
        "hr_lower": 0.3623,
        "hr_upper": 0.9589,
        "p_value": 0.033253,
        "significant": true
      },
      "genre_Punk": {
        "coef": 0.7169,
        "hr": 2.0481,
        "hr_lower": 0.8909,
        "hr_upper": 4.7084,
        "p_value": 0.091396,
        "significant": false
      },
      "genre_Soul/R&B": {
        "coef": -0.2719,
        "hr": 0.7619,
        "hr_lower": 0.4037,
        "hr_upper": 1.438,
        "p_value": 0.401429,
        "significant": false
      },
      "era_post2000": {
        "coef": 0.5626,
        "hr": 1.7552,
        "hr_lower": 1.2219,
        "hr_upper": 2.5215,
        "p_value": 0.002333,
        "significant": true
      }
    },
    "n_observations": 256,
    "concordance": 0.6341,
    "note": "Hazard ratio < 1 means SLOWER induction (longer wait). HR of 0.5 means 50% lower annual probability of induction.",
    "causation_caveat": "This model documents DISPARITIES in induction rates. It does NOT prove intentional discrimination. Observational data, correlation only."
  },
  "survival_curves": {
    "White male, Classic Rock": {
      "timeline": [
        0.0,
        1.0,
        2.0,
        3.0,
        4.0,
        5.0,
        6.0,
        7.0,
        8.0,
        9.0,
        10.0,
        11.0,
        12.0,
        13.0,
        14.0,
        15.0,
        16.0,
        17.0,
        18.0,
        20.0,
        21.0,
        22.0,
        23.0,
        24.0,
        25.0,
        26.0,
        27.0,
        29.0,
        30.0
      ],
      "survival": [
        0.9464,
        0.8036,
        0.7411,
        0.7054,
        0.6071,
        0.5446,
        0.4821,
        0.4464,
        0.4107,
        0.4018,
        0.375,
        0.3482,
        0.3214,
        0.2946,
        0.2589,
        0.2232,
        0.2054,
        0.1786,
        0.1607,
        0.1429,
        0.1339,
        0.0893,
        0.0625,
        0.0536,
        0.0446,
        0.0357,
        0.0179,
        0.0089,
        0.0
      ],
      "median_wait": 6.0,
      "n": 112
    },
    "Black artist, Soul/R&B": {
      "timeline": [
        0.0,
        1.0,
        2.0,
        3.0,
        4.0,
        5.0,
        6.0,
        7.0,
        8.0,
        9.0,
        10.0,
        12.0,
        13.0,
        14.0,
        15.0,
        16.0,
        17.0,
        18.0,
        19.0,
        20.0,
        21.0,
        22.0,
        23.0,
        24.0,
        27.0,
        29.0,
        30.0,
        35.0,
        36.0,
        37.0
      ],
      "survival": [
        1.0,
        0.9545,
        0.8939,
        0.8636,
        0.8485,
        0.7879,
        0.7424,
        0.697,
        0.6515,
        0.6212,
        0.5606,
        0.4545,
        0.3939,
        0.3636,
        0.3333,
        0.3182,
        0.303,
        0.2727,
        0.2576,
        0.2424,
        0.1818,
        0.1667,
        0.1212,
        0.1061,
        0.0909,
        0.0758,
        0.0606,
        0.0303,
        0.0152,
        0.0
      ],
      "median_wait": 12.0,
      "n": 66
    },
    "Female artist": {
      "timeline": [
        0.0,
        1.0,
        2.0,
        4.0,
        5.0,
        8.0,
        10.0,
        11.0,
        12.0,
        13.0,
        14.0,
        17.0,
        18.0,
        19.0,
        20.0,
        21.0,
        24.0,
        26.0,
        30.0,
        32.0,
        35.0,
        36.0
      ],
      "survival": [
        1.0,
        0.9355,
        0.9032,
        0.8387,
        0.7742,
        0.7097,
        0.6774,
        0.6452,
        0.5806,
        0.5161,
        0.4516,
        0.4194,
        0.3871,
        0.3548,
        0.2903,
        0.2258,
        0.1935,
        0.129,
        0.0968,
        0.0645,
        0.0323,
        0.0
      ],
      "median_wait": 14.0,
      "n": 31
    },
    "Heavy Metal artist": {
      "timeline": [
        0.0,
        1.0,
        6.0,
        12.0,
        21.0,
        29.0
      ],
      "survival": [
        1.0,
        0.8,
        0.6,
        0.4,
        0.2,
        0.0
      ],
      "median_wait": 12.0,
      "n": 5
    }
  },
  "wait_statistics": {
    "All inducted": {
      "n": 256,
      "median_wait": 9.5,
      "mean_wait": 11.3,
      "max_wait": 42,
      "pct_first_eligible": 15.2
    },
    "Black artists": {
      "n": 86,
      "median_wait": 10.0,
      "mean_wait": 12.2,
      "max_wait": 37,
      "pct_first_eligible": 10.5
    },
    "White artists": {
      "n": 167,
      "median_wait": 8.0,
      "mean_wait": 10.7,
      "max_wait": 42,
      "pct_first_eligible": 18.0
    },
    "Female artists": {
      "n": 31,
      "median_wait": 14.0,
      "mean_wait": 15.5,
      "max_wait": 36,
      "pct_first_eligible": 6.5
    },
    "Male artists": {
      "n": 95,
      "median_wait": 12.0,
      "mean_wait": 12.3,
      "max_wait": 42,
      "pct_first_eligible": 9.5
    },
    "Groups": {
      "n": 130,
      "median_wait": 6.0,
      "mean_wait": 9.6,
      "max_wait": 37,
      "pct_first_eligible": 21.5
    },
    "Classic Rock": {
      "n": 123,
      "median_wait": 6.0,
      "mean_wait": 9.3,
      "max_wait": 30,
      "pct_first_eligible": 17.9
    },
    "Soul/R&B": {
      "n": 69,
      "median_wait": 12.0,
      "mean_wait": 13.7,
      "max_wait": 37,
      "pct_first_eligible": 4.3
    },
    "Heavy Metal": {
      "n": 5,
      "median_wait": 12.0,
      "mean_wait": 13.8,
      "max_wait": 29,
      "pct_first_eligible": 20.0
    },
    "Hip-Hop": {
      "n": 12,
      "median_wait": 1.0,
      "mean_wait": 3.1,
      "max_wait": 9,
      "pct_first_eligible": 58.3
    },
    "Punk": {
      "n": 8,
      "median_wait": 3.0,
      "mean_wait": 4.5,
      "max_wait": 16,
      "pct_first_eligible": 50.0
    },
    "Pop": {
      "n": 25,
      "median_wait": 17.0,
      "mean_wait": 17.3,
      "max_wait": 36,
      "pct_first_eligible": 4.0
    }
  },
  "metal_cases": [
    {
      "name": "Ozzy Osbourne",
      "eligible_year": 1995,
      "inducted_year": 2024,
      "wait_years": 29
    },
    {
      "name": "Deep Purple",
      "eligible_year": 1993,
      "inducted_year": 2016,
      "wait_years": 23
    },
    {
      "name": "Iron Maiden",
      "eligible_year": 2005,
      "inducted_year": 2026,
      "wait_years": 21
    },
    {
      "name": "Def Leppard",
      "eligible_year": 2005,
      "inducted_year": 2019,
      "wait_years": 14
    },
    {
      "name": "Black Sabbath",
      "eligible_year": 1994,
      "inducted_year": 2006,
      "wait_years": 12
    },
    {
      "name": "Rage Against the Machine",
      "eligible_year": 2017,
      "inducted_year": 2023,
      "wait_years": 6
    },
    {
      "name": "AC/DC",
      "eligible_year": 1998,
      "inducted_year": 2003,
      "wait_years": 5
    },
    {
      "name": "Van Halen",
      "eligible_year": 2003,
      "inducted_year": 2007,
      "wait_years": 4
    },
    {
      "name": "Guns N' Roses",
      "eligible_year": 2010,
      "inducted_year": 2012,
      "wait_years": 2
    },
    {
      "name": "Metallica",
      "eligible_year": 2008,
      "inducted_year": 2009,
      "wait_years": 1
    }
  ],
  "metadata": {
    "source": "Rock and Roll Hall of Fame official inductee database",
    "model_type": "Cox Proportional Hazards (lifelines library)",
    "censoring": "No right-censoring in current model (inducted performers only). Full model would add eligible non-inducted artists as right-censored.",
    "baseline": "White male Classic Rock artist, eligible pre-2000",
    "n_artists_in_model": 256
  },
  "too_late": [
    {"name": "The Notorious B.I.G.", "inducted": 2020, "died": 1997, "gap": 23, "race": "Black", "genre": "Hip-Hop"},
    {"name": "Tupac Shakur", "inducted": 2017, "died": 1996, "gap": 21, "race": "Black", "genre": "Hip-Hop"},
    {"name": "Link Wray", "inducted": 2023, "died": 2005, "gap": 18, "race": "Native American", "genre": "Rock"},
    {"name": "Laura Nyro", "inducted": 2012, "died": 1997, "gap": 15, "race": "white", "genre": "Rock"},
    {"name": "Nina Simone", "inducted": 2018, "died": 2003, "gap": 15, "race": "Black", "genre": "Jazz/Soul"},
    {"name": "Whitney Houston", "inducted": 2020, "died": 2012, "gap": 8, "race": "Black", "genre": "Pop/R&B"},
    {"name": "Phife Dawg (A Tribe Called Quest)", "inducted": 2024, "died": 2016, "gap": 8, "race": "Black", "genre": "Hip-Hop"},
    {"name": "Donna Summer", "inducted": 2013, "died": 2012, "gap": 1, "race": "Black", "genre": "Disco"},
    {"name": "Dusty Springfield", "inducted": 1999, "died": 1999, "gap": 0, "race": "white", "genre": "Pop/Soul"}
  ],
  "died_waiting": [
    {"name": "Big Mama Thornton", "died": 1984, "genre": "Blues", "race": "Black", "note": "Wrote 'Hound Dog.' Elvis: first class. Thornton: never."},
    {"name": "Phil Lynott", "died": 1986, "genre": "Hard Rock", "race": "Black", "note": "Thin Lizzy never inducted."},
    {"name": "Lemmy Kilmister", "died": 2015, "genre": "Heavy Metal", "race": "white", "note": "Motorhead never inducted as Performers."},
    {"name": "Chris Cornell", "died": 2017, "genre": "Grunge", "race": "white", "note": "Soundgarden never inducted."},
    {"name": "Dick Dale", "died": 2019, "genre": "Surf Rock", "race": "white", "note": "Invented surf guitar. Never inducted."},
    {"name": "Wayne Kramer", "died": 2024, "genre": "Punk", "race": "white", "note": "MC5 inducted months after his death."}
  ]
};
