// One Long Impersonation -- Chapter 02: The Wait
// D3 visualization engine for survival analysis exhibits
// Reads from window.WAIT_DATA (generated by pipeline)

(function() {
  'use strict';

  var data = window.WAIT_DATA;
  if (!data) {
    console.error('[wait-engine] No data found. Run pipeline first.');
    return;
  }

  // Design tokens (read from CSS vars at runtime, with fallbacks)
  var COLORS = {
    ink:       '#14142b',
    cream:     '#efe8d6',
    cream2:    '#d8cfb6',
    gold:      '#d4a017',
    goldHot:   '#e8b727',
    blood:     '#b03434',
    bloodDeep: '#7a1f1f',
    moss:      '#5f7d56',
    mute:      '#8a8aa3',
    rule:      '#2e2e55',
    paper:     '#f1ece1',
    bone:      '#f6f2ea'
  };

  // Stratum colors
  var CURVE_COLORS = {
    'White male, Classic Rock': COLORS.cream2,
    'Black artist, Soul/R&B':   COLORS.gold,
    'Female artist':            COLORS.blood,
    'Heavy Metal artist':       COLORS.moss
  };

  // -------------------------------------------------------
  // Populate headline statistics
  // -------------------------------------------------------
  function populateStats() {
    var ws = data.wait_statistics;

    var mappings = [
      { id: 'stat-female-wait',  key: 'Female artists',  field: 'median_wait' },
      { id: 'stat-male-wait',    key: 'Male artists',    field: 'median_wait' },
      { id: 'stat-black-wait',   key: 'Black artists',   field: 'median_wait' },
      { id: 'stat-white-wait',   key: 'White artists',   field: 'median_wait' },
      { id: 'stat-metal-wait',   key: 'Heavy Metal',     field: 'median_wait' },
      { id: 'stat-hiphop-wait',  key: 'Hip-Hop',         field: 'median_wait' }
    ];

    mappings.forEach(function(m) {
      var el = document.getElementById(m.id);
      if (el && ws[m.key] && ws[m.key][m.field] != null) {
        el.textContent = ws[m.key][m.field];
      }
    });

    var nEl = document.getElementById('stat-n-artists');
    if (nEl && ws['All inducted']) {
      nEl.textContent = ws['All inducted'].n;
    }
  }

  // -------------------------------------------------------
  // Crosshair corner ticks (forensic exhibit framing)
  // -------------------------------------------------------
  function drawCrosshairs(svg, width, height) {
    var tickLen = 12;
    var tickStroke = 'rgba(212,160,23,0.4)';
    var off = 4;

    var corners = [
      { x1: off, y1: off, dx: tickLen, dy: 0 },
      { x1: off, y1: off, dx: 0, dy: tickLen },
      { x1: width - off, y1: off, dx: -tickLen, dy: 0 },
      { x1: width - off, y1: off, dx: 0, dy: tickLen },
      { x1: off, y1: height - off, dx: tickLen, dy: 0 },
      { x1: off, y1: height - off, dx: 0, dy: -tickLen },
      { x1: width - off, y1: height - off, dx: -tickLen, dy: 0 },
      { x1: width - off, y1: height - off, dx: 0, dy: -tickLen }
    ];

    corners.forEach(function(c) {
      svg.append('line')
        .attr('x1', c.x1).attr('y1', c.y1)
        .attr('x2', c.x1 + c.dx).attr('y2', c.y1 + c.dy)
        .attr('stroke', tickStroke)
        .attr('stroke-width', 1);
    });
  }

  // -------------------------------------------------------
  // Ex. 002-A: Survival Curves (Kaplan-Meier)
  // -------------------------------------------------------
  function renderSurvivalCurves() {
    var container = document.getElementById('survival-chart');
    if (!container) return;

    var curves = data.survival_curves;
    var strataKeys = Object.keys(curves);

    // Dimensions
    var margin = { top: 48, right: 200, bottom: 60, left: 72 };
    var width = Math.max(container.clientWidth, 700);
    var chartHeight = 400;
    var height = chartHeight + margin.top + margin.bottom;

    // Scales
    var xMax = 38;
    var x = d3.scaleLinear()
      .domain([0, xMax])
      .range([margin.left, width - margin.right]);

    var y = d3.scaleLinear()
      .domain([0, 1])
      .range([height - margin.bottom, margin.top]);

    // Create SVG
    var svg = d3.select(container)
      .append('svg')
      .attr('width', width)
      .attr('height', height)
      .attr('viewBox', '0 0 ' + width + ' ' + height)
      .attr('role', 'img')
      .attr('aria-label', 'Kaplan-Meier survival curves showing time-to-induction for 4 artist strata');

    // Background
    svg.append('rect')
      .attr('width', width)
      .attr('height', height)
      .attr('fill', COLORS.ink);

    // Crosshair exhibit framing
    drawCrosshairs(svg, width, height);

    // Grid lines -- horizontal
    var yTicks = [0, 0.25, 0.5, 0.75, 1.0];
    yTicks.forEach(function(t) {
      svg.append('line')
        .attr('x1', margin.left).attr('x2', width - margin.right)
        .attr('y1', y(t)).attr('y2', y(t))
        .attr('stroke', COLORS.rule)
        .attr('stroke-width', 1);

      svg.append('text')
        .attr('x', margin.left - 12)
        .attr('y', y(t) + 4)
        .attr('text-anchor', 'end')
        .attr('fill', COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 10)
        .text(Math.round(t * 100) + '%');
    });

    // Grid lines -- vertical
    var xTicks = d3.range(0, xMax + 1, 5);
    xTicks.forEach(function(t) {
      svg.append('line')
        .attr('x1', x(t)).attr('x2', x(t))
        .attr('y1', margin.top).attr('y2', height - margin.bottom)
        .attr('stroke', COLORS.rule)
        .attr('stroke-width', 1);

      svg.append('text')
        .attr('x', x(t))
        .attr('y', height - margin.bottom + 20)
        .attr('text-anchor', 'middle')
        .attr('fill', COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 10)
        .text(t);
    });

    // Axis labels
    svg.append('text')
      .attr('x', (margin.left + width - margin.right) / 2)
      .attr('y', height - 10)
      .attr('text-anchor', 'middle')
      .attr('fill', COLORS.mute)
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 11)
      .attr('letter-spacing', '0.08em')
      .text('YEARS SINCE ELIGIBILITY');

    svg.append('text')
      .attr('transform', 'rotate(-90)')
      .attr('x', -(margin.top + chartHeight / 2))
      .attr('y', 16)
      .attr('text-anchor', 'middle')
      .attr('fill', COLORS.mute)
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 11)
      .attr('letter-spacing', '0.08em')
      .text('% STILL NOT INDUCTED');

    // Median wait dashed line at 50%
    svg.append('line')
      .attr('x1', margin.left).attr('x2', width - margin.right)
      .attr('y1', y(0.5)).attr('y2', y(0.5))
      .attr('stroke', COLORS.cream2)
      .attr('stroke-width', 1)
      .attr('stroke-dasharray', '6,4')
      .attr('opacity', 0.5);

    svg.append('text')
      .attr('x', margin.left + 4)
      .attr('y', y(0.5) - 6)
      .attr('fill', COLORS.cream2)
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 9)
      .attr('opacity', 0.6)
      .text('MEDIAN');

    // Step-after line generator
    var line = d3.line()
      .x(function(d) { return x(d[0]); })
      .y(function(d) { return y(d[1]); })
      .curve(d3.curveStepAfter);

    // Draw each survival curve
    strataKeys.forEach(function(key, si) {
      var stratum = curves[key];
      var color = CURVE_COLORS[key] || COLORS.mute;

      // Build point pairs from timeline + survival arrays
      var points = stratum.timeline.map(function(t, i) {
        return [t, stratum.survival[i]];
      });

      // Prepend (0, 1.0) if not present
      if (points[0][0] !== 0 || points[0][1] !== 1.0) {
        points.unshift([0, 1.0]);
      }

      // Dash patterns for accessibility (not color-only)
      var dashPatterns = ['', '8,4', '4,4', '12,4,4,4'];
      var dashPattern = dashPatterns[si] || '';

      // Draw the curve
      svg.append('path')
        .datum(points)
        .attr('d', line)
        .attr('fill', 'none')
        .attr('stroke', color)
        .attr('stroke-width', 2.5)
        .attr('stroke-dasharray', dashPattern)
        .attr('opacity', 0.9);

      // Median wait vertical drop indicator
      if (stratum.median_wait != null) {
        svg.append('line')
          .attr('x1', x(stratum.median_wait))
          .attr('x2', x(stratum.median_wait))
          .attr('y1', y(0.5))
          .attr('y2', y(0.5) + 8)
          .attr('stroke', color)
          .attr('stroke-width', 1.5)
          .attr('opacity', 0.7);

        svg.append('circle')
          .attr('cx', x(stratum.median_wait))
          .attr('cy', y(0.5))
          .attr('r', 3.5)
          .attr('fill', color)
          .attr('stroke', COLORS.ink)
          .attr('stroke-width', 1.5);
      }
    });

    // Legend
    var legendX = width - margin.right + 20;
    var legendY = margin.top + 16;

    svg.append('text')
      .attr('x', legendX)
      .attr('y', legendY - 8)
      .attr('fill', COLORS.mute)
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 9)
      .attr('letter-spacing', '0.12em')
      .text('STRATUM');

    strataKeys.forEach(function(key, i) {
      var stratum = curves[key];
      var color = CURVE_COLORS[key] || COLORS.mute;
      var ly = legendY + i * 40 + 12;

      // Color swatch line
      svg.append('line')
        .attr('x1', legendX).attr('x2', legendX + 20)
        .attr('y1', ly).attr('y2', ly)
        .attr('stroke', color)
        .attr('stroke-width', 2.5);

      // Label
      svg.append('text')
        .attr('x', legendX + 28)
        .attr('y', ly + 4)
        .attr('fill', color)
        .attr('font-family', '"Inter", sans-serif')
        .attr('font-size', 11)
        .attr('font-weight', 500)
        .text(key);

      // Median + n
      svg.append('text')
        .attr('x', legendX + 28)
        .attr('y', ly + 18)
        .attr('fill', COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 9)
        .text('median ' + stratum.median_wait + 'y | n=' + stratum.n);
    });
  }

  // -------------------------------------------------------
  // Ex. 002-B: Metal Wait Bars
  // -------------------------------------------------------
  function renderMetalBars() {
    var container = document.getElementById('metal-chart');
    if (!container) return;

    var cases = data.metal_cases;

    // Sort by wait_years descending
    cases.sort(function(a, b) { return b.wait_years - a.wait_years; });

    // Dimensions
    var margin = { top: 40, right: 120, bottom: 40, left: 200 };
    var barHeight = 36;
    var barGap = 6;
    var width = Math.max(container.clientWidth, 600);
    var height = margin.top + cases.length * (barHeight + barGap) + margin.bottom;

    var maxWait = d3.max(cases, function(d) { return d.wait_years; });

    var x = d3.scaleLinear()
      .domain([0, maxWait + 2])
      .range([margin.left, width - margin.right]);

    // Create SVG
    var svg = d3.select(container)
      .append('svg')
      .attr('width', width)
      .attr('height', height)
      .attr('viewBox', '0 0 ' + width + ' ' + height)
      .attr('role', 'img')
      .attr('aria-label', 'Horizontal bar chart of metal artist wait times for Rock Hall induction');

    // Background
    svg.append('rect')
      .attr('width', width)
      .attr('height', height)
      .attr('fill', COLORS.ink);

    // Crosshair exhibit framing
    var tickLen = 12;
    var tickStroke = 'rgba(176,52,52,0.3)';
    var off = 4;
    var corners = [
      { x1: off, y1: off, dx: tickLen, dy: 0 },
      { x1: off, y1: off, dx: 0, dy: tickLen },
      { x1: width - off, y1: off, dx: -tickLen, dy: 0 },
      { x1: width - off, y1: off, dx: 0, dy: tickLen },
      { x1: off, y1: height - off, dx: tickLen, dy: 0 },
      { x1: off, y1: height - off, dx: 0, dy: -tickLen },
      { x1: width - off, y1: height - off, dx: -tickLen, dy: 0 },
      { x1: width - off, y1: height - off, dx: 0, dy: -tickLen }
    ];
    corners.forEach(function(c) {
      svg.append('line')
        .attr('x1', c.x1).attr('y1', c.y1)
        .attr('x2', c.x1 + c.dx).attr('y2', c.y1 + c.dy)
        .attr('stroke', tickStroke)
        .attr('stroke-width', 1);
    });

    // Vertical grid lines
    d3.range(0, maxWait + 3, 5).forEach(function(t) {
      svg.append('line')
        .attr('x1', x(t)).attr('x2', x(t))
        .attr('y1', margin.top).attr('y2', height - margin.bottom)
        .attr('stroke', COLORS.rule)
        .attr('stroke-width', 1);

      svg.append('text')
        .attr('x', x(t))
        .attr('y', height - margin.bottom + 18)
        .attr('text-anchor', 'middle')
        .attr('fill', COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 10)
        .text(t + 'y');
    });

    // Render each bar
    cases.forEach(function(d, i) {
      var cy = margin.top + i * (barHeight + barGap) + barHeight / 2;
      var barTop = cy - barHeight / 2 + 3;
      var barBot = cy + barHeight / 2 - 3;
      var barH = barBot - barTop;

      // Artist name (left label)
      svg.append('text')
        .attr('x', margin.left - 12)
        .attr('y', cy + 5)
        .attr('text-anchor', 'end')
        .attr('fill', COLORS.cream)
        .attr('font-family', '"Inter", sans-serif')
        .attr('font-size', 13)
        .attr('font-weight', 500)
        .text(d.name);

      // Bar fill -- gold for standard Performer induction
      svg.append('rect')
        .attr('x', x(0))
        .attr('y', barTop)
        .attr('width', x(d.wait_years) - x(0))
        .attr('height', barH)
        .attr('fill', COLORS.gold)
        .attr('rx', 2)
        .attr('opacity', 0.85);

      // Right label: wait years + eligible-inducted range
      svg.append('text')
        .attr('x', x(d.wait_years) + 8)
        .attr('y', cy + 1)
        .attr('fill', COLORS.cream)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 11)
        .attr('font-weight', 600)
        .attr('letter-spacing', '0.06em')
        .text(d.wait_years + 'y');

      svg.append('text')
        .attr('x', x(d.wait_years) + 8)
        .attr('y', cy + 14)
        .attr('fill', COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 9)
        .text(d.eligible_year + ' \u2192 ' + d.inducted_year);
    });
  }

  // -------------------------------------------------------
  // Ex. 002-C: Cox Model Results
  // -------------------------------------------------------
  function renderCoxModel() {
    var container = document.getElementById('cox-results');
    if (!container) return;

    var hrs = data.cox_model.hazard_ratios;
    var keys = Object.keys(hrs);

    // Readable labels
    var labels = {
      'is_black':        'Black artist',
      'is_female':       'Female artist',
      'is_group':        'Group (vs. solo)',
      'genre_Blues/Early':'Blues / Early R&R',
      'genre_Folk/Country':'Folk / Country',
      'genre_Heavy Metal':'Heavy Metal',
      'genre_Hip-Hop':   'Hip-Hop',
      'genre_Pop':       'Pop',
      'genre_Punk':      'Punk',
      'genre_Soul/R&B':  'Soul / R&B',
      'era_post2000':    'Eligible post-2000'
    };

    // Header row
    var header = document.createElement('div');
    header.className = 'cox-row cox-row--header';
    header.innerHTML =
      '<div class="cox-row__label">Covariate</div>' +
      '<div class="cox-row__hr" style="text-align:right">HR</div>' +
      '<div class="cox-row__bar"></div>' +
      '<div class="cox-row__p" style="text-align:right">p-value</div>';
    container.appendChild(header);

    // HR range for bar scaling
    var allHR = keys.map(function(k) { return hrs[k].hr; });
    var minHR = Math.min.apply(null, allHR);
    var maxHR = Math.max.apply(null, allHR);
    var hrRange = Math.max(maxHR, 1 / minHR);

    keys.forEach(function(key) {
      var h = hrs[key];
      var row = document.createElement('div');
      row.className = 'cox-row';

      var label = labels[key] || key;
      var hrText = h.hr.toFixed(2);
      var pText = h.p_value < 0.001 ? '<0.001' : h.p_value.toFixed(3);
      var sigClass = h.significant ? ' cox-row__p--sig' : '';

      // Bar: center at HR=1.0, extend left (slower) or right (faster)
      var barColor = h.hr < 1 ? COLORS.blood : COLORS.moss;
      var barWidth, barLeft;

      // Normalize: log scale conceptually, but use linear for simplicity
      // Center of bar area = HR 1.0
      var barAreaWidth = 100; // percentage
      if (h.hr < 1) {
        barWidth = ((1 - h.hr) / (1 - 0.2)) * 50;
        barLeft = 50 - barWidth;
      } else {
        barWidth = ((h.hr - 1) / (hrRange - 1)) * 50;
        barLeft = 50;
      }

      row.innerHTML =
        '<div class="cox-row__label">' + label + '</div>' +
        '<div class="cox-row__hr" style="color:' + barColor + '">' + hrText + '</div>' +
        '<div class="cox-row__bar">' +
          '<div class="cox-row__bar-center" style="left:50%"></div>' +
          '<div class="cox-row__bar-fill" style="left:' + barLeft + '%; width:' + Math.max(barWidth, 2) + '%; background:' + barColor + '"></div>' +
        '</div>' +
        '<div class="cox-row__p' + sigClass + '">' + pText + '</div>';

      container.appendChild(row);
    });

    // Update caveat text from data
    var caveatEl = document.getElementById('cox-caveat');
    if (caveatEl && data.cox_model.causation_caveat) {
      caveatEl.textContent = data.cox_model.causation_caveat;
    }
  }

  // -------------------------------------------------------
  // Initialize
  // -------------------------------------------------------
  function init() {
    populateStats();
    renderSurvivalCurves();
    renderMetalBars();
    renderCoxModel();
  }

  // -------------------------------------------------------
  // Ex. 002-D: Too Late -- Posthumous and died-waiting
  // -------------------------------------------------------
  function renderTooLate() {
    var container = document.getElementById('too-late-chart');
    if (!container) return;

    var tooLate = data.too_late || [];
    var diedWaiting = data.died_waiting || [];
    var all = [];

    tooLate.forEach(function(d) {
      all.push({ name: d.name, died: d.died, inducted: d.inducted, gap: d.gap, race: d.race, genre: d.genre, type: 'posthumous' });
    });
    diedWaiting.forEach(function(d) {
      all.push({ name: d.name, died: d.died, inducted: null, gap: 2026 - d.died, race: d.race, genre: d.genre, type: 'never', note: d.note });
    });

    all.sort(function(a, b) { return b.gap - a.gap; });

    var html = '<div style="display:flex; flex-direction:column; gap:2px">';

    all.forEach(function(d) {
      var isNever = d.type === 'never';
      var barColor = isNever ? COLORS.blood : COLORS.gold;
      var barWidth = Math.min(d.gap / 30 * 100, 100);
      var label = isNever ? 'NEVER INDUCTED' : 'Inducted ' + d.inducted;
      var labelColor = isNever ? COLORS.blood : COLORS.mute;

      html +=
        '<div style="display:grid; grid-template-columns:200px 1fr 100px; align-items:center; padding:10px 0; border-bottom:1px solid rgba(46,46,85,0.4)">' +
          '<div>' +
            '<span style="font-family:var(--serif); font-size:15px; font-weight:500; color:' + (isNever ? COLORS.blood : 'var(--cream)') + '">' + d.name + '</span>' +
            '<span style="font-family:var(--mono); font-size:9px; color:var(--mute); margin-left:8px">d. ' + d.died + '</span>' +
          '</div>' +
          '<div style="position:relative; height:16px; background:rgba(46,46,85,0.3); border-radius:2px; overflow:hidden">' +
            '<div style="position:absolute; left:0; top:0; height:100%; width:' + barWidth + '%; background:' + barColor + '; opacity:0.7; border-radius:2px"></div>' +
            '<span style="position:absolute; left:8px; top:1px; font-family:var(--mono); font-size:10px; color:var(--cream); font-weight:600">' + d.gap + ' years</span>' +
          '</div>' +
          '<div style="text-align:right; font-family:var(--mono); font-size:9px; letter-spacing:0.08em; color:' + labelColor + '">' + label + '</div>' +
        '</div>';
    });

    html += '</div>';
    container.innerHTML = html;
  }

  function init() {
    try { populateStats(); } catch(e) { console.error('[wait] populateStats:', e); }
    try { renderSurvivalCurves(); } catch(e) { console.error('[wait] survivalCurves:', e); }
    try { renderMetalDocket(); } catch(e) { console.error('[wait] metalDocket:', e); }
    try { renderCoxModel(); } catch(e) { console.error('[wait] coxModel:', e); }
    try { renderTooLate(); } catch(e) { console.error('[wait] tooLate:', e); }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
