// One Long Impersonation -- Chapter 00: The Criteria
// Criteria Compliance Model output -- generated by pipeline
// 113 eligible artists scored

window.CRITERIA_DATA = {
  "violation_index": [
    {
      "name": "Rosetta Tharpe",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1963,
      "wait_years": 63,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Mississippi John Hurt",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1953,
      "wait_years": 73,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Blind Willie McTell",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1952,
      "wait_years": 74,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Lonnie Johnson",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1950,
      "wait_years": 76,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Tampa Red",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1953,
      "wait_years": 73,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Big Bill Broonzy",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1952,
      "wait_years": 74,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Son House",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1955,
      "wait_years": 71,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Kraftwerk",
      "criteria_score": 48.4,
      "genre": "Electronic",
      "eligible_year": 1995,
      "wait_years": 31,
      "gap_vs_inducted_median": 6.4,
      "above_inducted_median": true
    },
    {
      "name": "The Meters",
      "criteria_score": 44.3,
      "genre": "Soul/R&B",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": 2.3,
      "above_inducted_median": true
    },
    {
      "name": "War",
      "criteria_score": 44.3,
      "genre": "Soul/R&B",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": 2.3,
      "above_inducted_median": true
    },
    {
      "name": "Tangerine Dream",
      "criteria_score": 43.45,
      "genre": "Electronic",
      "eligible_year": 1992,
      "wait_years": 34,
      "gap_vs_inducted_median": 1.45,
      "above_inducted_median": true
    },
    {
      "name": "Iron Butterfly",
      "criteria_score": 42.6,
      "genre": "Heavy Metal",
      "eligible_year": 1993,
      "wait_years": 33,
      "gap_vs_inducted_median": 0.6,
      "above_inducted_median": true
    },
    {
      "name": "The Kingston Trio",
      "criteria_score": 42.0,
      "genre": "Folk/Country",
      "eligible_year": 1983,
      "wait_years": 43,
      "gap_vs_inducted_median": 0.0,
      "above_inducted_median": false
    },
    {
      "name": "Jethro Tull",
      "criteria_score": 40.9,
      "genre": "Classic Rock",
      "eligible_year": 1993,
      "wait_years": 33,
      "gap_vs_inducted_median": -1.1,
      "above_inducted_median": false
    },
    {
      "name": "King Crimson",
      "criteria_score": 40.9,
      "genre": "Classic Rock",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": -1.1,
      "above_inducted_median": false
    },
    {
      "name": "Chaka Khan",
      "criteria_score": 40.6,
      "genre": "Soul/R&B",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": -1.4,
      "above_inducted_median": false
    },
    {
      "name": "Rufus featuring Chaka Khan",
      "criteria_score": 40.6,
      "genre": "Soul/R&B",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": -1.4,
      "above_inducted_median": false
    },
    {
      "name": "The Commodores",
      "criteria_score": 40.6,
      "genre": "Soul/R&B",
      "eligible_year": 1999,
      "wait_years": 27,
      "gap_vs_inducted_median": -1.4,
      "above_inducted_median": false
    },
    {
      "name": "Gordon Lightfoot",
      "criteria_score": 40.2,
      "genre": "Folk/Country",
      "eligible_year": 1991,
      "wait_years": 35,
      "gap_vs_inducted_median": -1.8,
      "above_inducted_median": false
    },
    {
      "name": "Gloria Gaynor",
      "criteria_score": 40.2,
      "genre": "Disco/Dance",
      "eligible_year": 1990,
      "wait_years": 36,
      "gap_vs_inducted_median": -1.8,
      "above_inducted_median": false
    },
    {
      "name": "Brian Eno",
      "criteria_score": 39.9,
      "genre": "Electronic",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": -2.1,
      "above_inducted_median": false
    },
    {
      "name": "Thin Lizzy",
      "criteria_score": 39.2,
      "genre": "Heavy Metal",
      "eligible_year": 1996,
      "wait_years": 30,
      "gap_vs_inducted_median": -2.8,
      "above_inducted_median": false
    },
    {
      "name": "Scorpions",
      "criteria_score": 39.2,
      "genre": "Heavy Metal",
      "eligible_year": 1997,
      "wait_years": 29,
      "gap_vs_inducted_median": -2.8,
      "above_inducted_median": false
    },
    {
      "name": "Townes Van Zandt",
      "criteria_score": 39.2,
      "genre": "Folk/Country",
      "eligible_year": 1993,
      "wait_years": 33,
      "gap_vs_inducted_median": -2.8,
      "above_inducted_median": false
    },
    {
      "name": "Emmylou Harris",
      "criteria_score": 39.2,
      "genre": "Folk/Country",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": -2.8,
      "above_inducted_median": false
    },
    {
      "name": "Rick James",
      "criteria_score": 39.0,
      "genre": "Soul/R&B",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": -3.0,
      "above_inducted_median": false
    },
    {
      "name": "Joy Division",
      "criteria_score": 38.85,
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": -3.15,
      "above_inducted_median": false
    },
    {
      "name": "Emerson Lake & Palmer",
      "criteria_score": 38.8,
      "genre": "Classic Rock",
      "eligible_year": 1995,
      "wait_years": 31,
      "gap_vs_inducted_median": -3.2,
      "above_inducted_median": false
    },
    {
      "name": "Bjork",
      "criteria_score": 38.6,
      "genre": "Electronic",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -3.4,
      "above_inducted_median": false
    },
    {
      "name": "The Damned",
      "criteria_score": 38.2,
      "genre": "Punk",
      "eligible_year": 2001,
      "wait_years": 25,
      "gap_vs_inducted_median": -3.8,
      "above_inducted_median": false
    },
    {
      "name": "Motorhead",
      "criteria_score": 37.9,
      "genre": "Heavy Metal",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -4.1,
      "above_inducted_median": false
    },
    {
      "name": "Wire",
      "criteria_score": 37.9,
      "genre": "Punk",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -4.1,
      "above_inducted_median": false
    },
    {
      "name": "The Misfits",
      "criteria_score": 37.9,
      "genre": "Punk",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -4.1,
      "above_inducted_median": false
    },
    {
      "name": "Styx",
      "criteria_score": 37.8,
      "genre": "Classic Rock",
      "eligible_year": 1997,
      "wait_years": 29,
      "gap_vs_inducted_median": -4.2,
      "above_inducted_median": false
    },
    {
      "name": "REO Speedwagon",
      "criteria_score": 37.8,
      "genre": "Classic Rock",
      "eligible_year": 1996,
      "wait_years": 30,
      "gap_vs_inducted_median": -4.2,
      "above_inducted_median": false
    },
    {
      "name": "Teena Marie",
      "criteria_score": 37.7,
      "genre": "Soul/R&B",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -4.3,
      "above_inducted_median": false
    },
    {
      "name": "Siouxsie and the Banshees",
      "criteria_score": 37.6,
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": -4.4,
      "above_inducted_median": false
    },
    {
      "name": "The Fall",
      "criteria_score": 37.6,
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": -4.4,
      "above_inducted_median": false
    },
    {
      "name": "Boston",
      "criteria_score": 36.8,
      "genre": "Classic Rock",
      "eligible_year": 2001,
      "wait_years": 25,
      "gap_vs_inducted_median": -5.2,
      "above_inducted_median": false
    },
    {
      "name": "John Prine",
      "criteria_score": 36.4,
      "genre": "Folk/Country",
      "eligible_year": 1996,
      "wait_years": 30,
      "gap_vs_inducted_median": -5.6,
      "above_inducted_median": false
    },
    {
      "name": "KC and the Sunshine Band",
      "criteria_score": 36.4,
      "genre": "Disco/Dance",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": -5.6,
      "above_inducted_median": false
    },
    {
      "name": "The Pointer Sisters",
      "criteria_score": 36.4,
      "genre": "Disco/Dance",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": -5.6,
      "above_inducted_median": false
    },
    {
      "name": "Dead Kennedys",
      "criteria_score": 36.3,
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -5.7,
      "above_inducted_median": false
    },
    {
      "name": "Bauhaus",
      "criteria_score": 36.3,
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -5.7,
      "above_inducted_median": false
    },
    {
      "name": "Descendents",
      "criteria_score": 36.3,
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -5.7,
      "above_inducted_median": false
    },
    {
      "name": "New Order",
      "criteria_score": 35.1,
      "genre": "Electronic",
      "eligible_year": 2006,
      "wait_years": 20,
      "gap_vs_inducted_median": -6.9,
      "above_inducted_median": false
    },
    {
      "name": "Chic",
      "criteria_score": 35.1,
      "genre": "Disco/Dance",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -6.9,
      "above_inducted_median": false
    },
    {
      "name": "Oingo Boingo",
      "criteria_score": 34.9,
      "genre": "Classic Rock",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -7.1,
      "above_inducted_median": false
    },
    {
      "name": "Luther Vandross",
      "criteria_score": 34.4,
      "genre": "Soul/R&B",
      "eligible_year": 2006,
      "wait_years": 20,
      "gap_vs_inducted_median": -7.6,
      "above_inducted_median": false
    },
    {
      "name": "Lucinda Williams",
      "criteria_score": 33.5,
      "genre": "Folk/Country",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -8.5,
      "above_inducted_median": false
    }
  ],
  "inducted_average_score": 44.58,
  "inducted_median_score": 42.0,
  "total_eligible": 113,
  "above_inducted_median": 12,
  "weights": {
    "excellence": 0.25,
    "influence": 0.25,
    "career_length": 0.15,
    "catalog_depth": 0.15,
    "genre_contribution": 0.2
  },
  "metadata": {
    "source": "Criteria Compliance Model v1 (pipeline/src/models/criteria_compliance.py)",
    "method": "Weighted composite of 5 criteria proxies. See CLAUDE.md for weight documentation.",
    "note": "This model is a CONSTRUCT. The weights are documented, not derived. Sensitivity analysis should be performed before publication."
  }
};
