// One Long Impersonation -- Chapter 00: The Criteria
// Criteria Compliance Model output -- generated by pipeline
// 112 eligible artists scored

window.CRITERIA_DATA = {
  "violation_index": [
    {
      "name": "Joy Division",
      "criteria_score": 58.98,
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": 16.98,
      "above_inducted_median": true
    },
    {
      "name": "King Crimson",
      "criteria_score": 56.96,
      "genre": "Classic Rock",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": 14.96,
      "above_inducted_median": true
    },
    {
      "name": "Brian Eno",
      "criteria_score": 55.65,
      "genre": "Electronic",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": 13.65,
      "above_inducted_median": true
    },
    {
      "name": "Emerson Lake & Palmer",
      "criteria_score": 50.5,
      "genre": "Classic Rock",
      "eligible_year": 1995,
      "wait_years": 31,
      "gap_vs_inducted_median": 8.5,
      "above_inducted_median": true
    },
    {
      "name": "Mississippi John Hurt",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1953,
      "wait_years": 73,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Blind Willie McTell",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1952,
      "wait_years": 74,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Lonnie Johnson",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1950,
      "wait_years": 76,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Tampa Red",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1953,
      "wait_years": 73,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Big Bill Broonzy",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1952,
      "wait_years": 74,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Son House",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1955,
      "wait_years": 71,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Kraftwerk",
      "criteria_score": 48.4,
      "genre": "Electronic",
      "eligible_year": 1995,
      "wait_years": 31,
      "gap_vs_inducted_median": 6.4,
      "above_inducted_median": true
    },
    {
      "name": "The Meters",
      "criteria_score": 48.05,
      "genre": "Soul/R&B",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": 6.05,
      "above_inducted_median": true
    },
    {
      "name": "Jethro Tull",
      "criteria_score": 47.91,
      "genre": "Classic Rock",
      "eligible_year": 1993,
      "wait_years": 33,
      "gap_vs_inducted_median": 5.91,
      "above_inducted_median": true
    },
    {
      "name": "Bjork",
      "criteria_score": 47.66,
      "genre": "Electronic",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": 5.66,
      "above_inducted_median": true
    },
    {
      "name": "Chic",
      "criteria_score": 47.61,
      "genre": "Disco/Dance",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": 5.61,
      "above_inducted_median": true
    },
    {
      "name": "Chaka Khan",
      "criteria_score": 47.09,
      "genre": "Soul/R&B",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": 5.09,
      "above_inducted_median": true
    },
    {
      "name": "Thin Lizzy",
      "criteria_score": 46.7,
      "genre": "Heavy Metal",
      "eligible_year": 1996,
      "wait_years": 30,
      "gap_vs_inducted_median": 4.7,
      "above_inducted_median": true
    },
    {
      "name": "Scorpions",
      "criteria_score": 46.7,
      "genre": "Heavy Metal",
      "eligible_year": 1997,
      "wait_years": 29,
      "gap_vs_inducted_median": 4.7,
      "above_inducted_median": true
    },
    {
      "name": "Iron Butterfly",
      "criteria_score": 46.35,
      "genre": "Heavy Metal",
      "eligible_year": 1993,
      "wait_years": 33,
      "gap_vs_inducted_median": 4.35,
      "above_inducted_median": true
    },
    {
      "name": "Sonic Youth",
      "criteria_score": 46.26,
      "genre": "Punk",
      "eligible_year": 2007,
      "wait_years": 19,
      "gap_vs_inducted_median": 4.26,
      "above_inducted_median": true
    },
    {
      "name": "Siouxsie and the Banshees",
      "criteria_score": 45.77,
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": 3.77,
      "above_inducted_median": true
    },
    {
      "name": "New Order",
      "criteria_score": 44.77,
      "genre": "Electronic",
      "eligible_year": 2006,
      "wait_years": 20,
      "gap_vs_inducted_median": 2.77,
      "above_inducted_median": true
    },
    {
      "name": "Gordon Lightfoot",
      "criteria_score": 44.72,
      "genre": "Folk/Country",
      "eligible_year": 1991,
      "wait_years": 35,
      "gap_vs_inducted_median": 2.72,
      "above_inducted_median": true
    },
    {
      "name": "Dead Kennedys",
      "criteria_score": 44.56,
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": 2.56,
      "above_inducted_median": true
    },
    {
      "name": "The Smiths",
      "criteria_score": 44.4,
      "genre": "Classic Rock",
      "eligible_year": 2009,
      "wait_years": 17,
      "gap_vs_inducted_median": 2.4,
      "above_inducted_median": true
    },
    {
      "name": "War",
      "criteria_score": 44.3,
      "genre": "Soul/R&B",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": 2.3,
      "above_inducted_median": true
    },
    {
      "name": "Wire",
      "criteria_score": 43.93,
      "genre": "Punk",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": 1.93,
      "above_inducted_median": true
    },
    {
      "name": "Bauhaus",
      "criteria_score": 43.8,
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": 1.8,
      "above_inducted_median": true
    },
    {
      "name": "The Replacements",
      "criteria_score": 43.48,
      "genre": "Punk",
      "eligible_year": 2006,
      "wait_years": 20,
      "gap_vs_inducted_median": 1.48,
      "above_inducted_median": true
    },
    {
      "name": "Tangerine Dream",
      "criteria_score": 43.45,
      "genre": "Electronic",
      "eligible_year": 1992,
      "wait_years": 34,
      "gap_vs_inducted_median": 1.45,
      "above_inducted_median": true
    },
    {
      "name": "Husker Du",
      "criteria_score": 43.2,
      "genre": "Punk",
      "eligible_year": 2006,
      "wait_years": 20,
      "gap_vs_inducted_median": 1.2,
      "above_inducted_median": true
    },
    {
      "name": "Pixies",
      "criteria_score": 43.14,
      "genre": "Punk",
      "eligible_year": 2012,
      "wait_years": 14,
      "gap_vs_inducted_median": 1.14,
      "above_inducted_median": true
    },
    {
      "name": "Emmylou Harris",
      "criteria_score": 42.95,
      "genre": "Folk/Country",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": 0.95,
      "above_inducted_median": true
    },
    {
      "name": "Bad Brains",
      "criteria_score": 42.36,
      "genre": "Punk",
      "eligible_year": 2007,
      "wait_years": 19,
      "gap_vs_inducted_median": 0.36,
      "above_inducted_median": true
    },
    {
      "name": "The Kingston Trio",
      "criteria_score": 42.0,
      "genre": "Folk/Country",
      "eligible_year": 1983,
      "wait_years": 43,
      "gap_vs_inducted_median": 0.0,
      "above_inducted_median": false
    },
    {
      "name": "The Damned",
      "criteria_score": 41.95,
      "genre": "Punk",
      "eligible_year": 2001,
      "wait_years": 25,
      "gap_vs_inducted_median": -0.05,
      "above_inducted_median": false
    },
    {
      "name": "Styx",
      "criteria_score": 41.67,
      "genre": "Classic Rock",
      "eligible_year": 1997,
      "wait_years": 29,
      "gap_vs_inducted_median": -0.33,
      "above_inducted_median": false
    },
    {
      "name": "Boston",
      "criteria_score": 40.97,
      "genre": "Classic Rock",
      "eligible_year": 2001,
      "wait_years": 25,
      "gap_vs_inducted_median": -1.03,
      "above_inducted_median": false
    },
    {
      "name": "John Prine",
      "criteria_score": 40.75,
      "genre": "Folk/Country",
      "eligible_year": 1996,
      "wait_years": 30,
      "gap_vs_inducted_median": -1.25,
      "above_inducted_median": false
    },
    {
      "name": "Rufus featuring Chaka Khan",
      "criteria_score": 40.6,
      "genre": "Soul/R&B",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": -1.4,
      "above_inducted_median": false
    },
    {
      "name": "The Commodores",
      "criteria_score": 40.6,
      "genre": "Soul/R&B",
      "eligible_year": 1999,
      "wait_years": 27,
      "gap_vs_inducted_median": -1.4,
      "above_inducted_median": false
    },
    {
      "name": "Soundgarden",
      "criteria_score": 40.52,
      "genre": "Heavy Metal",
      "eligible_year": 2013,
      "wait_years": 13,
      "gap_vs_inducted_median": -1.48,
      "above_inducted_median": false
    },
    {
      "name": "OutKast",
      "criteria_score": 40.23,
      "genre": "Hip-Hop",
      "eligible_year": 2019,
      "wait_years": 7,
      "gap_vs_inducted_median": -1.77,
      "above_inducted_median": false
    },
    {
      "name": "Gloria Gaynor",
      "criteria_score": 40.2,
      "genre": "Disco/Dance",
      "eligible_year": 1990,
      "wait_years": 36,
      "gap_vs_inducted_median": -1.8,
      "above_inducted_median": false
    },
    {
      "name": "Kanye West",
      "criteria_score": 39.88,
      "genre": "Hip-Hop",
      "eligible_year": 2026,
      "wait_years": 0,
      "gap_vs_inducted_median": -2.12,
      "above_inducted_median": false
    },
    {
      "name": "Townes Van Zandt",
      "criteria_score": 39.2,
      "genre": "Folk/Country",
      "eligible_year": 1993,
      "wait_years": 33,
      "gap_vs_inducted_median": -2.8,
      "above_inducted_median": false
    },
    {
      "name": "Rick James",
      "criteria_score": 39.0,
      "genre": "Soul/R&B",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": -3.0,
      "above_inducted_median": false
    },
    {
      "name": "Motorhead",
      "criteria_score": 38.83,
      "genre": "Heavy Metal",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -3.17,
      "above_inducted_median": false
    },
    {
      "name": "REO Speedwagon",
      "criteria_score": 38.02,
      "genre": "Classic Rock",
      "eligible_year": 1996,
      "wait_years": 30,
      "gap_vs_inducted_median": -3.98,
      "above_inducted_median": false
    },
    {
      "name": "The Fall",
      "criteria_score": 37.95,
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": -4.05,
      "above_inducted_median": false
    }
  ],
  "inducted_average_score": 43.93,
  "inducted_median_score": 42.0,
  "total_eligible": 112,
  "above_inducted_median": 34,
  "weights": {
    "excellence": 0.25,
    "influence": 0.25,
    "career_length": 0.15,
    "catalog_depth": 0.15,
    "genre_contribution": 0.2
  },
  "metadata": {
    "source": "Criteria Compliance Model v1 (pipeline/src/models/criteria_compliance.py)",
    "method": "Weighted composite of 5 criteria proxies. See CLAUDE.md for weight documentation.",
    "note": "This model is a CONSTRUCT. The weights are documented, not derived. Sensitivity analysis should be performed before publication."
  }
};
