// One Long Impersonation -- Chapter 00: The Criteria
// Criteria Compliance Model output -- generated by pipeline
// 112 eligible artists scored

window.CRITERIA_DATA = {
  "violation_index": [
    {
      "name": "Mississippi John Hurt",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1953,
      "wait_years": 73,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Blind Willie McTell",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1952,
      "wait_years": 74,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Lonnie Johnson",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1950,
      "wait_years": 76,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Tampa Red",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1953,
      "wait_years": 73,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Big Bill Broonzy",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1952,
      "wait_years": 74,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Son House",
      "criteria_score": 50.0,
      "genre": "Blues/Early",
      "eligible_year": 1955,
      "wait_years": 71,
      "gap_vs_inducted_median": 8.0,
      "above_inducted_median": true
    },
    {
      "name": "Kraftwerk",
      "criteria_score": 48.4,
      "genre": "Electronic",
      "eligible_year": 1995,
      "wait_years": 31,
      "gap_vs_inducted_median": 6.4,
      "above_inducted_median": true
    },
    {
      "name": "The Meters",
      "criteria_score": 48.05,
      "genre": "Soul/R&B",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": 6.05,
      "above_inducted_median": true
    },
    {
      "name": "Joy Division",
      "criteria_score": 47.73,
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": 5.73,
      "above_inducted_median": true
    },
    {
      "name": "Bjork",
      "criteria_score": 47.66,
      "genre": "Electronic",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": 5.66,
      "above_inducted_median": true
    },
    {
      "name": "Thin Lizzy",
      "criteria_score": 46.7,
      "genre": "Heavy Metal",
      "eligible_year": 1996,
      "wait_years": 30,
      "gap_vs_inducted_median": 4.7,
      "above_inducted_median": true
    },
    {
      "name": "King Crimson",
      "criteria_score": 45.71,
      "genre": "Classic Rock",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": 3.71,
      "above_inducted_median": true
    },
    {
      "name": "Brian Eno",
      "criteria_score": 44.4,
      "genre": "Electronic",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": 2.4,
      "above_inducted_median": true
    },
    {
      "name": "War",
      "criteria_score": 44.3,
      "genre": "Soul/R&B",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": 2.3,
      "above_inducted_median": true
    },
    {
      "name": "Jethro Tull",
      "criteria_score": 44.16,
      "genre": "Classic Rock",
      "eligible_year": 1993,
      "wait_years": 33,
      "gap_vs_inducted_median": 2.16,
      "above_inducted_median": true
    },
    {
      "name": "Tangerine Dream",
      "criteria_score": 43.45,
      "genre": "Electronic",
      "eligible_year": 1992,
      "wait_years": 34,
      "gap_vs_inducted_median": 1.45,
      "above_inducted_median": true
    },
    {
      "name": "Chaka Khan",
      "criteria_score": 43.34,
      "genre": "Soul/R&B",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": 1.34,
      "above_inducted_median": true
    },
    {
      "name": "Emerson Lake & Palmer",
      "criteria_score": 43.0,
      "genre": "Classic Rock",
      "eligible_year": 1995,
      "wait_years": 31,
      "gap_vs_inducted_median": 1.0,
      "above_inducted_median": true
    },
    {
      "name": "Iron Butterfly",
      "criteria_score": 42.6,
      "genre": "Heavy Metal",
      "eligible_year": 1993,
      "wait_years": 33,
      "gap_vs_inducted_median": 0.6,
      "above_inducted_median": true
    },
    {
      "name": "The Kingston Trio",
      "criteria_score": 42.0,
      "genre": "Folk/Country",
      "eligible_year": 1983,
      "wait_years": 43,
      "gap_vs_inducted_median": 0.0,
      "above_inducted_median": false
    },
    {
      "name": "New Order",
      "criteria_score": 41.02,
      "genre": "Electronic",
      "eligible_year": 2006,
      "wait_years": 20,
      "gap_vs_inducted_median": -0.98,
      "above_inducted_median": false
    },
    {
      "name": "Gordon Lightfoot",
      "criteria_score": 40.97,
      "genre": "Folk/Country",
      "eligible_year": 1991,
      "wait_years": 35,
      "gap_vs_inducted_median": -1.03,
      "above_inducted_median": false
    },
    {
      "name": "Rufus featuring Chaka Khan",
      "criteria_score": 40.6,
      "genre": "Soul/R&B",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": -1.4,
      "above_inducted_median": false
    },
    {
      "name": "The Commodores",
      "criteria_score": 40.6,
      "genre": "Soul/R&B",
      "eligible_year": 1999,
      "wait_years": 27,
      "gap_vs_inducted_median": -1.4,
      "above_inducted_median": false
    },
    {
      "name": "Gloria Gaynor",
      "criteria_score": 40.2,
      "genre": "Disco/Dance",
      "eligible_year": 1990,
      "wait_years": 36,
      "gap_vs_inducted_median": -1.8,
      "above_inducted_median": false
    },
    {
      "name": "Wire",
      "criteria_score": 40.18,
      "genre": "Punk",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -1.82,
      "above_inducted_median": false
    },
    {
      "name": "Chic",
      "criteria_score": 40.11,
      "genre": "Disco/Dance",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -1.89,
      "above_inducted_median": false
    },
    {
      "name": "Scorpions",
      "criteria_score": 39.2,
      "genre": "Heavy Metal",
      "eligible_year": 1997,
      "wait_years": 29,
      "gap_vs_inducted_median": -2.8,
      "above_inducted_median": false
    },
    {
      "name": "Townes Van Zandt",
      "criteria_score": 39.2,
      "genre": "Folk/Country",
      "eligible_year": 1993,
      "wait_years": 33,
      "gap_vs_inducted_median": -2.8,
      "above_inducted_median": false
    },
    {
      "name": "Emmylou Harris",
      "criteria_score": 39.2,
      "genre": "Folk/Country",
      "eligible_year": 1994,
      "wait_years": 32,
      "gap_vs_inducted_median": -2.8,
      "above_inducted_median": false
    },
    {
      "name": "Rick James",
      "criteria_score": 39.0,
      "genre": "Soul/R&B",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": -3.0,
      "above_inducted_median": false
    },
    {
      "name": "Motorhead",
      "criteria_score": 38.83,
      "genre": "Heavy Metal",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -3.17,
      "above_inducted_median": false
    },
    {
      "name": "Sonic Youth",
      "criteria_score": 38.76,
      "genre": "Punk",
      "eligible_year": 2007,
      "wait_years": 19,
      "gap_vs_inducted_median": -3.24,
      "above_inducted_median": false
    },
    {
      "name": "Siouxsie and the Banshees",
      "criteria_score": 38.27,
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": -3.73,
      "above_inducted_median": false
    },
    {
      "name": "The Damned",
      "criteria_score": 38.2,
      "genre": "Punk",
      "eligible_year": 2001,
      "wait_years": 25,
      "gap_vs_inducted_median": -3.8,
      "above_inducted_median": false
    },
    {
      "name": "REO Speedwagon",
      "criteria_score": 38.02,
      "genre": "Classic Rock",
      "eligible_year": 1996,
      "wait_years": 30,
      "gap_vs_inducted_median": -3.98,
      "above_inducted_median": false
    },
    {
      "name": "The Fall",
      "criteria_score": 37.95,
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "gap_vs_inducted_median": -4.05,
      "above_inducted_median": false
    },
    {
      "name": "Styx",
      "criteria_score": 37.92,
      "genre": "Classic Rock",
      "eligible_year": 1997,
      "wait_years": 29,
      "gap_vs_inducted_median": -4.08,
      "above_inducted_median": false
    },
    {
      "name": "The Misfits",
      "criteria_score": 37.9,
      "genre": "Punk",
      "eligible_year": 2002,
      "wait_years": 24,
      "gap_vs_inducted_median": -4.1,
      "above_inducted_median": false
    },
    {
      "name": "Teena Marie",
      "criteria_score": 37.7,
      "genre": "Soul/R&B",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -4.3,
      "above_inducted_median": false
    },
    {
      "name": "Luther Vandross",
      "criteria_score": 37.45,
      "genre": "Soul/R&B",
      "eligible_year": 2006,
      "wait_years": 20,
      "gap_vs_inducted_median": -4.55,
      "above_inducted_median": false
    },
    {
      "name": "Boston",
      "criteria_score": 37.22,
      "genre": "Classic Rock",
      "eligible_year": 2001,
      "wait_years": 25,
      "gap_vs_inducted_median": -4.78,
      "above_inducted_median": false
    },
    {
      "name": "Dead Kennedys",
      "criteria_score": 37.06,
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -4.94,
      "above_inducted_median": false
    },
    {
      "name": "John Prine",
      "criteria_score": 37.0,
      "genre": "Folk/Country",
      "eligible_year": 1996,
      "wait_years": 30,
      "gap_vs_inducted_median": -5.0,
      "above_inducted_median": false
    },
    {
      "name": "The Smiths",
      "criteria_score": 36.9,
      "genre": "Classic Rock",
      "eligible_year": 2009,
      "wait_years": 17,
      "gap_vs_inducted_median": -5.1,
      "above_inducted_median": false
    },
    {
      "name": "KC and the Sunshine Band",
      "criteria_score": 36.4,
      "genre": "Disco/Dance",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": -5.6,
      "above_inducted_median": false
    },
    {
      "name": "The Pointer Sisters",
      "criteria_score": 36.4,
      "genre": "Disco/Dance",
      "eligible_year": 1998,
      "wait_years": 28,
      "gap_vs_inducted_median": -5.6,
      "above_inducted_median": false
    },
    {
      "name": "Bauhaus",
      "criteria_score": 36.3,
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -5.7,
      "above_inducted_median": false
    },
    {
      "name": "Descendents",
      "criteria_score": 36.3,
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "gap_vs_inducted_median": -5.7,
      "above_inducted_median": false
    },
    {
      "name": "Kanye West",
      "criteria_score": 36.12,
      "genre": "Hip-Hop",
      "eligible_year": 2026,
      "wait_years": 0,
      "gap_vs_inducted_median": -5.88,
      "above_inducted_median": false
    }
  ],
  "inducted_average_score": 43.69,
  "inducted_median_score": 42.0,
  "total_eligible": 112,
  "above_inducted_median": 19,
  "weights": {
    "excellence": 0.25,
    "influence": 0.25,
    "career_length": 0.15,
    "catalog_depth": 0.15,
    "genre_contribution": 0.2
  },
  "metadata": {
    "source": "Criteria Compliance Model v1 (pipeline/src/models/criteria_compliance.py)",
    "method": "Weighted composite of 5 criteria proxies. See CLAUDE.md for weight documentation.",
    "note": "This model is a CONSTRUCT. The weights are documented, not derived. Sensitivity analysis should be performed before publication."
  }
};
