// One Long Impersonation -- Chapter 03: Genre Desertification
// D3 visualization engine for genre diversity exhibits
// Reads from window.GENRE_DATA (generated by pipeline)

(function() {
  'use strict';

  var data = window.GENRE_DATA;
  if (!data) {
    console.error('[genre-engine] No data found. Run pipeline first.');
    return;
  }

  // Design tokens (fallbacks matching design-tokens.css)
  var COLORS = {
    ink:       '#14142b',
    ink2:      '#1d1d3a',
    cream:     '#efe8d6',
    cream2:    '#d8cfb6',
    gold:      '#d4a017',
    goldHot:   '#e8b727',
    blood:     '#b03434',
    bloodDeep: '#7a1f1f',
    moss:      '#5f7d56',
    mute:      '#8a8aa3',
    rule:      '#2e2e55',
    paper:     '#f1ece1',
    bone:      '#f6f2ea'
  };

  var GENRES = data.genre_taxonomy;
  var GENRE_COLORS = data.genre_colors;
  var WENNER_EXIT = 2019;

  // -------------------------------------------------------
  // Crosshair corner ticks (forensic exhibit framing)
  // -------------------------------------------------------
  function drawCrosshairs(svg, width, height, color) {
    var tickLen = 12;
    var tickStroke = color || 'rgba(212,160,23,0.4)';
    var off = 4;

    var corners = [
      { x1: off, y1: off, dx: tickLen, dy: 0 },
      { x1: off, y1: off, dx: 0, dy: tickLen },
      { x1: width - off, y1: off, dx: -tickLen, dy: 0 },
      { x1: width - off, y1: off, dx: 0, dy: tickLen },
      { x1: off, y1: height - off, dx: tickLen, dy: 0 },
      { x1: off, y1: height - off, dx: 0, dy: -tickLen },
      { x1: width - off, y1: height - off, dx: -tickLen, dy: 0 },
      { x1: width - off, y1: height - off, dx: 0, dy: -tickLen }
    ];

    corners.forEach(function(c) {
      svg.append('line')
        .attr('x1', c.x1).attr('y1', c.y1)
        .attr('x2', c.x1 + c.dx).attr('y2', c.y1 + c.dy)
        .attr('stroke', tickStroke)
        .attr('stroke-width', 1);
    });
  }

  // -------------------------------------------------------
  // BIAS SCORE TABLE
  // -------------------------------------------------------
  function renderBiasTable() {
    var tbody = document.getElementById('bias-table-body');
    if (!tbody) return;

    var scores = data.genre_bias_scores;
    var html = '';

    GENRES.forEach(function(genre) {
      var s = scores[genre];
      if (!s) return;

      var color = GENRE_COLORS[genre] || COLORS.mute;
      var changeVal = s.change;
      var changeClass, arrow;

      if (changeVal > 0.1) {
        changeClass = 'change-up';
        arrow = '\u2191';
      } else if (changeVal < -0.1) {
        changeClass = 'change-down';
        arrow = '\u2193';
      } else {
        changeClass = 'change-flat';
        arrow = '\u2014';
      }

      var wennerText = s.wenner_bias.toFixed(2);
      var postText = s.post_wenner_bias.toFixed(2);
      var changeText = (changeVal >= 0 ? '+' : '') + changeVal.toFixed(2);

      html +=
        '<tr>' +
        '<td><span class="genre-dot" style="background:' + color + '"></span>' + genre + '</td>' +
        '<td>' + wennerText + '</td>' +
        '<td>' + postText + '</td>' +
        '<td class="' + changeClass + '">' + arrow + ' ' + changeText + '</td>' +
        '</tr>';
    });

    tbody.innerHTML = html;
  }

  // -------------------------------------------------------
  // Ex. 003-A: GENRE TIMELINE (stacked bars + Simpson line)
  // -------------------------------------------------------
  function renderTimeline() {
    var container = document.getElementById('genre-timeline');
    if (!container) return;

    var timeline = data.genre_timeline;
    var simpsonData = data.simpson_index;

    // Dimensions
    var margin = { top: 48, right: 180, bottom: 60, left: 56 };
    var rowHeight = 18;
    var rowGap = 3;
    var barSectionHeight = timeline.length * (rowHeight + rowGap);
    var simpsonHeight = 140;
    var gapBetween = 40;
    var width = Math.max(container.clientWidth, 700);
    var totalHeight = margin.top + barSectionHeight + gapBetween + simpsonHeight + margin.bottom;

    // Max total inductees in a year (for bar scale)
    var maxTotal = d3.max(timeline, function(d) {
      var sum = 0;
      GENRES.forEach(function(g) { sum += (d[g] || 0); });
      return sum;
    });

    var x = d3.scaleLinear()
      .domain([0, maxTotal])
      .range([0, width - margin.left - margin.right - 180]);

    // Create SVG
    var svg = d3.select(container)
      .append('svg')
      .attr('width', width)
      .attr('height', totalHeight)
      .attr('viewBox', '0 0 ' + width + ' ' + totalHeight)
      .attr('role', 'img')
      .attr('aria-label', 'Stacked bar chart of genre representation per year with Simpson diversity index');

    // Background
    svg.append('rect')
      .attr('width', width)
      .attr('height', totalHeight)
      .attr('fill', COLORS.ink);

    drawCrosshairs(svg, width, totalHeight);

    // Wenner era background tint
    var wennerEndIdx = -1;
    timeline.forEach(function(d, i) {
      if (d.year <= WENNER_EXIT) wennerEndIdx = i;
    });

    if (wennerEndIdx >= 0) {
      var wennerBottom = margin.top + (wennerEndIdx + 1) * (rowHeight + rowGap);
      svg.append('rect')
        .attr('x', margin.left - 8)
        .attr('y', margin.top - 4)
        .attr('width', width - margin.left - margin.right + 16)
        .attr('height', wennerBottom - margin.top + 8)
        .attr('fill', 'rgba(20,20,43,0.35)')
        .attr('rx', 2);
    }

    // Stacked bars, one row per year
    timeline.forEach(function(d, i) {
      var rowY = margin.top + i * (rowHeight + rowGap);
      var cumX = margin.left;

      // Year label
      svg.append('text')
        .attr('x', margin.left - 10)
        .attr('y', rowY + rowHeight / 2 + 4)
        .attr('text-anchor', 'end')
        .attr('fill', d.year === WENNER_EXIT ? COLORS.gold : COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 9)
        .attr('font-weight', d.year === WENNER_EXIT ? 600 : 400)
        .text(d.year);

      // Draw genre segments
      GENRES.forEach(function(genre) {
        var count = d[genre] || 0;
        if (count === 0) return;

        var segW = x(count);
        svg.append('rect')
          .attr('x', cumX)
          .attr('y', rowY)
          .attr('width', segW)
          .attr('height', rowHeight)
          .attr('fill', GENRE_COLORS[genre])
          .attr('rx', 1)
          .attr('opacity', 0.9);

        cumX += segW + 1;
      });
    });

    // Vertical dashed line at Wenner exit
    var wennerLineY1 = margin.top - 12;
    var wennerLineY2 = margin.top + barSectionHeight + gapBetween + simpsonHeight + 8;
    // Find y position at year 2019
    var wennerIdx = -1;
    timeline.forEach(function(d, i) { if (d.year === WENNER_EXIT) wennerIdx = i; });

    if (wennerIdx >= 0) {
      var wennerRowY = margin.top + wennerIdx * (rowHeight + rowGap) + rowHeight + rowGap / 2;

      // Horizontal dashed line across full width at the Wenner/Sykes boundary
      svg.append('line')
        .attr('x1', margin.left - 8)
        .attr('x2', width - margin.right + 8)
        .attr('y1', wennerRowY)
        .attr('y2', wennerRowY)
        .attr('stroke', COLORS.gold)
        .attr('stroke-width', 1)
        .attr('stroke-dasharray', '6,4')
        .attr('opacity', 0.6);

      svg.append('text')
        .attr('x', width - margin.right + 12)
        .attr('y', wennerRowY + 4)
        .attr('fill', COLORS.gold)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 9)
        .attr('letter-spacing', '0.1em')
        .attr('font-weight', 600)
        .text('WENNER EXITS');
    }

    // -- Simpson's Diversity Index line chart below --
    var simpsonTop = margin.top + barSectionHeight + gapBetween;
    var simpsonBot = simpsonTop + simpsonHeight;

    // Simpson Y scale
    var sY = d3.scaleLinear()
      .domain([0, 1])
      .range([simpsonBot, simpsonTop]);

    // Simpson X scale: map year range to same horizontal as bars
    var yearExtent = d3.extent(simpsonData, function(d) { return d.year; });
    var sX = d3.scaleLinear()
      .domain(yearExtent)
      .range([margin.left, width - margin.right]);

    // Background for simpson section
    svg.append('rect')
      .attr('x', margin.left - 8)
      .attr('y', simpsonTop - 4)
      .attr('width', width - margin.left - margin.right + 16)
      .attr('height', simpsonHeight + 8)
      .attr('fill', 'rgba(30,30,58,0.4)')
      .attr('rx', 2);

    // Label
    svg.append('text')
      .attr('x', margin.left)
      .attr('y', simpsonTop - 10)
      .attr('fill', COLORS.mute)
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 9)
      .attr('letter-spacing', '0.1em')
      .text('SIMPSON\'S DIVERSITY INDEX');

    // Horizontal grid lines for simpson
    [0, 0.25, 0.5, 0.75, 1.0].forEach(function(v) {
      svg.append('line')
        .attr('x1', margin.left).attr('x2', width - margin.right)
        .attr('y1', sY(v)).attr('y2', sY(v))
        .attr('stroke', COLORS.rule)
        .attr('stroke-width', 1)
        .attr('opacity', 0.5);

      svg.append('text')
        .attr('x', margin.left - 10)
        .attr('y', sY(v) + 3)
        .attr('text-anchor', 'end')
        .attr('fill', COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 8)
        .text(v.toFixed(2));
    });

    // Wenner exit vertical line in simpson chart
    if (wennerIdx >= 0) {
      svg.append('line')
        .attr('x1', sX(WENNER_EXIT))
        .attr('x2', sX(WENNER_EXIT))
        .attr('y1', simpsonTop)
        .attr('y2', simpsonBot)
        .attr('stroke', COLORS.gold)
        .attr('stroke-width', 1)
        .attr('stroke-dasharray', '6,4')
        .attr('opacity', 0.6);
    }

    // Area fill under the line
    var area = d3.area()
      .x(function(d) { return sX(d.year); })
      .y0(simpsonBot)
      .y1(function(d) { return sY(d.simpson); })
      .curve(d3.curveMonotoneX);

    svg.append('path')
      .datum(simpsonData)
      .attr('d', area)
      .attr('fill', COLORS.gold)
      .attr('opacity', 0.1);

    // The line itself
    var line = d3.line()
      .x(function(d) { return sX(d.year); })
      .y(function(d) { return sY(d.simpson); })
      .curve(d3.curveMonotoneX);

    svg.append('path')
      .datum(simpsonData)
      .attr('d', line)
      .attr('fill', 'none')
      .attr('stroke', COLORS.gold)
      .attr('stroke-width', 2)
      .attr('opacity', 0.85);

    // Dots on Simpson line
    simpsonData.forEach(function(d) {
      svg.append('circle')
        .attr('cx', sX(d.year))
        .attr('cy', sY(d.simpson))
        .attr('r', 2.5)
        .attr('fill', COLORS.gold)
        .attr('stroke', COLORS.ink)
        .attr('stroke-width', 1);
    });

    // Year labels on Simpson x-axis
    var yearTicks = simpsonData.filter(function(d) { return d.year % 5 === 0 || d.year === yearExtent[0] || d.year === yearExtent[1]; });
    yearTicks.forEach(function(d) {
      svg.append('text')
        .attr('x', sX(d.year))
        .attr('y', simpsonBot + 14)
        .attr('text-anchor', 'middle')
        .attr('fill', COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 8)
        .text(d.year);
    });

    // -- LEGEND (right side) --
    var legendX = width - margin.right + 20;
    var legendY = margin.top + 8;

    svg.append('text')
      .attr('x', legendX)
      .attr('y', legendY - 4)
      .attr('fill', COLORS.mute)
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 9)
      .attr('letter-spacing', '0.12em')
      .text('GENRES');

    GENRES.forEach(function(genre, i) {
      var ly = legendY + i * 22 + 12;
      var color = GENRE_COLORS[genre];

      // Color swatch
      svg.append('rect')
        .attr('x', legendX)
        .attr('y', ly - 5)
        .attr('width', 14)
        .attr('height', 10)
        .attr('fill', color)
        .attr('rx', 1)
        .attr('opacity', 0.9);

      // Label
      svg.append('text')
        .attr('x', legendX + 20)
        .attr('y', ly + 4)
        .attr('fill', COLORS.cream2)
        .attr('font-family', '"Inter", sans-serif')
        .attr('font-size', 10)
        .text(genre);
    });
  }

  // -------------------------------------------------------
  // SIMPSON'S INDEX ERA COMPARISON
  // -------------------------------------------------------
  function renderSimpsonCallout() {
    var container = document.getElementById('simpson-comparison');
    if (!container) return;

    var era = data.era_comparison;

    container.innerHTML =
      '<div class="simpson-era">' +
        '<div class="simpson-era__value display">' + era.wenner_era.simpson.toFixed(2) + '</div>' +
        '<div class="simpson-era__label smallcaps">Wenner Era</div>' +
        '<div class="simpson-era__years mono">' + era.wenner_era.years + '</div>' +
      '</div>' +
      '<div class="simpson-arrow">' +
        '<div class="simpson-arrow__icon">\u2192</div>' +
        '<div class="simpson-arrow__ratio">' + era.improvement_ratio.toFixed(2) + 'x</div>' +
      '</div>' +
      '<div class="simpson-era">' +
        '<div class="simpson-era__value display" style="color:var(--moss)">' + era.post_wenner.simpson.toFixed(2) + '</div>' +
        '<div class="simpson-era__label smallcaps">Post-Wenner</div>' +
        '<div class="simpson-era__years mono">' + era.post_wenner.years + '</div>' +
      '</div>';
  }

  // -------------------------------------------------------
  // NEVER-INDUCTED GALLERY
  // -------------------------------------------------------
  function renderGallery() {
    var container = document.getElementById('gallery-grid');
    if (!container) return;

    var artists = data.never_inducted_notable;
    var html = '';

    artists.forEach(function(a) {
      var color = GENRE_COLORS[a.genre] || COLORS.mute;
      var yearsWaiting = 2026 - a.eligible_year;

      html +=
        '<div class="gallery-card">' +
          '<div class="gallery-card__genre-tag" style="background:' + color + '">' + a.genre + '</div>' +
          '<div class="gallery-card__name">' + a.name + '</div>' +
          '<div class="gallery-card__eligible">Eligible since ' + a.eligible_year + ' (' + yearsWaiting + ' years)</div>' +
          '<div class="gallery-card__note">' + a.note + '</div>' +
        '</div>';
    });

    container.innerHTML = html;
  }

  // -------------------------------------------------------
  // Initialize
  // -------------------------------------------------------
  function init() {
    renderBiasTable();
    renderTimeline();
    renderSimpsonCallout();
    renderGallery();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
