// One Long Impersonation -- Chapter 03: Genre Desertification
// Genre diversity data -- generated by pipeline
// Method: Simpson's Diversity Index + Genre Bias Scores

window.GENRE_DATA = {
  "genre_timeline": [
    {
      "year": 1986,
      "Classic Rock": 5,
      "Soul/R&B": 4,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 1,
      "Disco/Dance": 0
    },
    {
      "year": 1987,
      "Classic Rock": 5,
      "Soul/R&B": 6,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 4,
      "Disco/Dance": 0
    },
    {
      "year": 1988,
      "Classic Rock": 3,
      "Soul/R&B": 2,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 1989,
      "Classic Rock": 2,
      "Soul/R&B": 3,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 1990,
      "Classic Rock": 2,
      "Soul/R&B": 3,
      "Pop": 1,
      "Folk/Country": 1,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 1991,
      "Classic Rock": 1,
      "Soul/R&B": 4,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 2,
      "Disco/Dance": 0
    },
    {
      "year": 1992,
      "Classic Rock": 2,
      "Soul/R&B": 3,
      "Pop": 0,
      "Folk/Country": 1,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 1,
      "Disco/Dance": 0
    },
    {
      "year": 1993,
      "Classic Rock": 4,
      "Soul/R&B": 4,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 1994,
      "Classic Rock": 8,
      "Soul/R&B": 0,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 1995,
      "Classic Rock": 5,
      "Soul/R&B": 2,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 1996,
      "Classic Rock": 4,
      "Soul/R&B": 3,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 1997,
      "Classic Rock": 3,
      "Soul/R&B": 2,
      "Pop": 0,
      "Folk/Country": 1,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 1
    },
    {
      "year": 1998,
      "Classic Rock": 5,
      "Soul/R&B": 1,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 1999,
      "Classic Rock": 4,
      "Soul/R&B": 2,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2000,
      "Classic Rock": 3,
      "Soul/R&B": 2,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2001,
      "Classic Rock": 4,
      "Soul/R&B": 2,
      "Pop": 1,
      "Folk/Country": 1,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2002,
      "Classic Rock": 1,
      "Soul/R&B": 1,
      "Pop": 2,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 2,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2003,
      "Classic Rock": 3,
      "Soul/R&B": 0,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 1,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2004,
      "Classic Rock": 5,
      "Soul/R&B": 1,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2005,
      "Classic Rock": 2,
      "Soul/R&B": 2,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 1,
      "Disco/Dance": 0
    },
    {
      "year": 2006,
      "Classic Rock": 1,
      "Soul/R&B": 0,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 1,
      "Punk": 2,
      "Electronic": 0,
      "Blues/Early": 1,
      "Disco/Dance": 0
    },
    {
      "year": 2007,
      "Classic Rock": 2,
      "Soul/R&B": 0,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 1,
      "Heavy Metal": 0,
      "Punk": 1,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2008,
      "Classic Rock": 3,
      "Soul/R&B": 0,
      "Pop": 1,
      "Folk/Country": 1,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2009,
      "Classic Rock": 1,
      "Soul/R&B": 2,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 1,
      "Heavy Metal": 1,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2010,
      "Classic Rock": 3,
      "Soul/R&B": 0,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 1,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2011,
      "Classic Rock": 2,
      "Soul/R&B": 0,
      "Pop": 2,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 1,
      "Disco/Dance": 0
    },
    {
      "year": 2012,
      "Classic Rock": 3,
      "Soul/R&B": 0,
      "Pop": 1,
      "Folk/Country": 1,
      "Hip-Hop": 1,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2013,
      "Classic Rock": 2,
      "Soul/R&B": 0,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 1,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 1,
      "Disco/Dance": 1
    },
    {
      "year": 2014,
      "Classic Rock": 3,
      "Soul/R&B": 0,
      "Pop": 2,
      "Folk/Country": 1,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2015,
      "Classic Rock": 3,
      "Soul/R&B": 1,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 1,
      "Electronic": 0,
      "Blues/Early": 2,
      "Disco/Dance": 0
    },
    {
      "year": 2016,
      "Classic Rock": 4,
      "Soul/R&B": 0,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 1,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2017,
      "Classic Rock": 4,
      "Soul/R&B": 0,
      "Pop": 0,
      "Folk/Country": 1,
      "Hip-Hop": 1,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2018,
      "Classic Rock": 4,
      "Soul/R&B": 1,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2019,
      "Classic Rock": 6,
      "Soul/R&B": 0,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2020,
      "Classic Rock": 2,
      "Soul/R&B": 0,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 1,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 2,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2021,
      "Classic Rock": 3,
      "Soul/R&B": 1,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 1,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2022,
      "Classic Rock": 1,
      "Soul/R&B": 1,
      "Pop": 3,
      "Folk/Country": 1,
      "Hip-Hop": 1,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2023,
      "Classic Rock": 1,
      "Soul/R&B": 1,
      "Pop": 2,
      "Folk/Country": 1,
      "Hip-Hop": 1,
      "Heavy Metal": 1,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2024,
      "Classic Rock": 3,
      "Soul/R&B": 1,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 2,
      "Heavy Metal": 1,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2025,
      "Classic Rock": 1,
      "Soul/R&B": 0,
      "Pop": 1,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 0,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    },
    {
      "year": 2026,
      "Classic Rock": 0,
      "Soul/R&B": 0,
      "Pop": 0,
      "Folk/Country": 0,
      "Hip-Hop": 0,
      "Heavy Metal": 1,
      "Punk": 0,
      "Electronic": 0,
      "Blues/Early": 0,
      "Disco/Dance": 0
    }
  ],
  "simpson_index": [
    {
      "year": 1986,
      "simpson": 0.58
    },
    {
      "year": 1987,
      "simpson": 0.6578
    },
    {
      "year": 1988,
      "simpson": 0.48
    },
    {
      "year": 1989,
      "simpson": 0.48
    },
    {
      "year": 1990,
      "simpson": 0.6939
    },
    {
      "year": 1991,
      "simpson": 0.5714
    },
    {
      "year": 1992,
      "simpson": 0.6939
    },
    {
      "year": 1993,
      "simpson": 0.5
    },
    {
      "year": 1994,
      "simpson": 0.0
    },
    {
      "year": 1995,
      "simpson": 0.4082
    },
    {
      "year": 1996,
      "simpson": 0.4898
    },
    {
      "year": 1997,
      "simpson": 0.6939
    },
    {
      "year": 1998,
      "simpson": 0.2778
    },
    {
      "year": 1999,
      "simpson": 0.5714
    },
    {
      "year": 2000,
      "simpson": 0.48
    },
    {
      "year": 2001,
      "simpson": 0.6562
    },
    {
      "year": 2002,
      "simpson": 0.7222
    },
    {
      "year": 2003,
      "simpson": 0.56
    },
    {
      "year": 2004,
      "simpson": 0.2778
    },
    {
      "year": 2005,
      "simpson": 0.64
    },
    {
      "year": 2006,
      "simpson": 0.72
    },
    {
      "year": 2007,
      "simpson": 0.72
    },
    {
      "year": 2008,
      "simpson": 0.56
    },
    {
      "year": 2009,
      "simpson": 0.72
    },
    {
      "year": 2010,
      "simpson": 0.56
    },
    {
      "year": 2011,
      "simpson": 0.64
    },
    {
      "year": 2012,
      "simpson": 0.6667
    },
    {
      "year": 2013,
      "simpson": 0.7778
    },
    {
      "year": 2014,
      "simpson": 0.6111
    },
    {
      "year": 2015,
      "simpson": 0.6939
    },
    {
      "year": 2016,
      "simpson": 0.32
    },
    {
      "year": 2017,
      "simpson": 0.5
    },
    {
      "year": 2018,
      "simpson": 0.32
    },
    {
      "year": 2019,
      "simpson": 0.2449
    },
    {
      "year": 2020,
      "simpson": 0.7222
    },
    {
      "year": 2021,
      "simpson": 0.6667
    },
    {
      "year": 2022,
      "simpson": 0.7347
    },
    {
      "year": 2023,
      "simpson": 0.8163
    },
    {
      "year": 2024,
      "simpson": 0.75
    },
    {
      "year": 2025,
      "simpson": 0.5
    },
    {
      "year": 2026,
      "simpson": 0.0
    }
  ],
  "genre_bias_scores": {
    "Classic Rock": {
      "wenner_count": 112,
      "post_wenner_count": 11,
      "total_count": 123,
      "wenner_share": 0.5114,
      "post_wenner_share": 0.2973,
      "overall_share": 0.4805,
      "wenner_bias": 1.06,
      "post_wenner_bias": 0.62,
      "change": -0.44
    },
    "Soul/R&B": {
      "wenner_count": 51,
      "post_wenner_count": 4,
      "total_count": 55,
      "wenner_share": 0.2329,
      "post_wenner_share": 0.1081,
      "overall_share": 0.2148,
      "wenner_bias": 1.08,
      "post_wenner_bias": 0.5,
      "change": -0.58
    },
    "Pop": {
      "wenner_count": 16,
      "post_wenner_count": 9,
      "total_count": 25,
      "wenner_share": 0.0731,
      "post_wenner_share": 0.2432,
      "overall_share": 0.0977,
      "wenner_bias": 0.75,
      "post_wenner_bias": 2.49,
      "change": 1.74
    },
    "Folk/Country": {
      "wenner_count": 8,
      "post_wenner_count": 2,
      "total_count": 10,
      "wenner_share": 0.0365,
      "post_wenner_share": 0.0541,
      "overall_share": 0.0391,
      "wenner_bias": 0.94,
      "post_wenner_bias": 1.38,
      "change": 0.44
    },
    "Hip-Hop": {
      "wenner_count": 6,
      "post_wenner_count": 6,
      "total_count": 12,
      "wenner_share": 0.0274,
      "post_wenner_share": 0.1622,
      "overall_share": 0.0469,
      "wenner_bias": 0.58,
      "post_wenner_bias": 3.46,
      "change": 2.88
    },
    "Heavy Metal": {
      "wenner_count": 2,
      "post_wenner_count": 3,
      "total_count": 5,
      "wenner_share": 0.0091,
      "post_wenner_share": 0.0811,
      "overall_share": 0.0195,
      "wenner_bias": 0.47,
      "post_wenner_bias": 4.15,
      "change": 3.68
    },
    "Punk": {
      "wenner_count": 8,
      "post_wenner_count": 0,
      "total_count": 8,
      "wenner_share": 0.0365,
      "post_wenner_share": 0.0,
      "overall_share": 0.0312,
      "wenner_bias": 1.17,
      "post_wenner_bias": 0.0,
      "change": -1.17
    },
    "Electronic": {
      "wenner_count": 0,
      "post_wenner_count": 2,
      "total_count": 2,
      "wenner_share": 0.0,
      "post_wenner_share": 0.0541,
      "overall_share": 0.0078,
      "wenner_bias": 0.0,
      "post_wenner_bias": 6.92,
      "change": 6.92
    },
    "Blues/Early": {
      "wenner_count": 14,
      "post_wenner_count": 0,
      "total_count": 14,
      "wenner_share": 0.0639,
      "post_wenner_share": 0.0,
      "overall_share": 0.0547,
      "wenner_bias": 1.17,
      "post_wenner_bias": 0.0,
      "change": -1.17
    },
    "Disco/Dance": {
      "wenner_count": 2,
      "post_wenner_count": 0,
      "total_count": 2,
      "wenner_share": 0.0091,
      "post_wenner_share": 0.0,
      "overall_share": 0.0078,
      "wenner_bias": 1.17,
      "post_wenner_bias": 0.0,
      "change": -1.17
    }
  },
  "era_comparison": {
    "wenner_era": {
      "simpson": 0.6712,
      "years": "1986-2019"
    },
    "post_wenner": {
      "simpson": 0.802,
      "years": "2020-2026"
    },
    "improvement_ratio": 1.19
  },
  "never_inducted_notable": [
    {
      "name": "Motorhead",
      "genre": "Heavy Metal",
      "eligible_year": 2002,
      "note": "Lemmy died 2015. Musical Excellence 2020 (not Performer)."
    },
    {
      "name": "Thin Lizzy",
      "genre": "Heavy Metal",
      "eligible_year": 1996,
      "note": "Phil Lynott died 1986. Never nominated."
    },
    {
      "name": "Soundgarden",
      "genre": "Heavy Metal",
      "eligible_year": 2016,
      "note": "Chris Cornell died 2017. Multiple nominations, never inducted."
    },
    {
      "name": "Tool",
      "genre": "Heavy Metal",
      "eligible_year": 2018,
      "note": "Consistently tops fan votes. Not inducted."
    },
    {
      "name": "System of a Down",
      "genre": "Heavy Metal",
      "eligible_year": 2023,
      "note": "Recently eligible. Not yet nominated."
    },
    {
      "name": "Bad Brains",
      "genre": "Punk",
      "eligible_year": 2007,
      "note": "Black punk pioneers. Never nominated."
    },
    {
      "name": "Kraftwerk",
      "genre": "Electronic",
      "eligible_year": 1995,
      "note": "Invented electronic music. Never inducted."
    },
    {
      "name": "New Order",
      "genre": "Electronic",
      "eligible_year": 2008,
      "note": "Bridged post-punk and electronic. Never nominated."
    },
    {
      "name": "Aphex Twin",
      "genre": "Electronic",
      "eligible_year": 2017,
      "note": "Most influential electronic artist. Never nominated."
    },
    {
      "name": "Iron Butterfly",
      "genre": "Heavy Metal",
      "eligible_year": 1993,
      "note": "Proto-metal pioneers. Never nominated."
    }
  ],
  "genre_colors": {
    "Classic Rock": "#d4a017",
    "Soul/R&B": "#b03434",
    "Pop": "#c47a3a",
    "Folk/Country": "#8a7d48",
    "Hip-Hop": "#5a6f8a",
    "Heavy Metal": "#3d4a5c",
    "Punk": "#7a4a8a",
    "Electronic": "#5f7d56",
    "Blues/Early": "#5c3a2a",
    "Disco/Dance": "#8a5a6f"
  },
  "genre_taxonomy": [
    "Classic Rock",
    "Soul/R&B",
    "Pop",
    "Folk/Country",
    "Hip-Hop",
    "Heavy Metal",
    "Punk",
    "Electronic",
    "Blues/Early",
    "Disco/Dance"
  ],
  "metadata": {
    "source": "Rock and Roll Hall of Fame official inductee database",
    "method": "Simpson's Diversity Index (1 - sum(p_i^2))",
    "bias_method": "Genre Bias Score = era genre share / overall genre share",
    "wenner_era": "1986-2019 (Wenner on nominating committee or as Chairman)",
    "post_wenner_era": "2020-2026 (John Sykes era)",
    "note": "Performer category only. Early Influence and Musical Excellence excluded."
  }
};
