// One Long Impersonation -- Chapter 05: The Docket
// Full docket with criteria scores -- generated by pipeline
// 113 eligible artists

window.DOCKET_DATA = {
  "artists": [
    {
      "name": "Rosetta Tharpe",
      "genre": "Blues/Early",
      "eligible_year": 1963,
      "wait_years": 63,
      "criteria_score": 50.0,
      "verdict": "STRONG_CASE"
    },
    {
      "name": "Mississippi John Hurt",
      "genre": "Blues/Early",
      "eligible_year": 1953,
      "wait_years": 73,
      "criteria_score": 50.0,
      "verdict": "STRONG_CASE"
    },
    {
      "name": "Blind Willie McTell",
      "genre": "Blues/Early",
      "eligible_year": 1952,
      "wait_years": 74,
      "criteria_score": 50.0,
      "verdict": "STRONG_CASE"
    },
    {
      "name": "Lonnie Johnson",
      "genre": "Blues/Early",
      "eligible_year": 1950,
      "wait_years": 76,
      "criteria_score": 50.0,
      "verdict": "STRONG_CASE"
    },
    {
      "name": "Tampa Red",
      "genre": "Blues/Early",
      "eligible_year": 1953,
      "wait_years": 73,
      "criteria_score": 50.0,
      "verdict": "STRONG_CASE"
    },
    {
      "name": "Big Bill Broonzy",
      "genre": "Blues/Early",
      "eligible_year": 1952,
      "wait_years": 74,
      "criteria_score": 50.0,
      "verdict": "STRONG_CASE"
    },
    {
      "name": "Son House",
      "genre": "Blues/Early",
      "eligible_year": 1955,
      "wait_years": 71,
      "criteria_score": 50.0,
      "verdict": "STRONG_CASE"
    },
    {
      "name": "Kraftwerk",
      "genre": "Electronic",
      "eligible_year": 1995,
      "wait_years": 31,
      "criteria_score": 48.4,
      "verdict": "CASE"
    },
    {
      "name": "The Meters",
      "genre": "Soul/R&B",
      "eligible_year": 1994,
      "wait_years": 32,
      "criteria_score": 44.3,
      "verdict": "CASE"
    },
    {
      "name": "War",
      "genre": "Soul/R&B",
      "eligible_year": 1994,
      "wait_years": 32,
      "criteria_score": 44.3,
      "verdict": "CASE"
    },
    {
      "name": "Tangerine Dream",
      "genre": "Electronic",
      "eligible_year": 1992,
      "wait_years": 34,
      "criteria_score": 43.45,
      "verdict": "CASE"
    },
    {
      "name": "Iron Butterfly",
      "genre": "Heavy Metal",
      "eligible_year": 1993,
      "wait_years": 33,
      "criteria_score": 42.6,
      "verdict": "CASE"
    },
    {
      "name": "The Kingston Trio",
      "genre": "Folk/Country",
      "eligible_year": 1983,
      "wait_years": 43,
      "criteria_score": 42.0,
      "verdict": "CASE"
    },
    {
      "name": "Jethro Tull",
      "genre": "Classic Rock",
      "eligible_year": 1993,
      "wait_years": 33,
      "criteria_score": 40.9,
      "verdict": "BORDERLINE"
    },
    {
      "name": "King Crimson",
      "genre": "Classic Rock",
      "eligible_year": 1994,
      "wait_years": 32,
      "criteria_score": 40.9,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Chaka Khan",
      "genre": "Soul/R&B",
      "eligible_year": 1998,
      "wait_years": 28,
      "criteria_score": 40.6,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Rufus featuring Chaka Khan",
      "genre": "Soul/R&B",
      "eligible_year": 1998,
      "wait_years": 28,
      "criteria_score": 40.6,
      "verdict": "BORDERLINE"
    },
    {
      "name": "The Commodores",
      "genre": "Soul/R&B",
      "eligible_year": 1999,
      "wait_years": 27,
      "criteria_score": 40.6,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Gordon Lightfoot",
      "genre": "Folk/Country",
      "eligible_year": 1991,
      "wait_years": 35,
      "criteria_score": 40.2,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Gloria Gaynor",
      "genre": "Disco/Dance",
      "eligible_year": 1990,
      "wait_years": 36,
      "criteria_score": 40.2,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Brian Eno",
      "genre": "Electronic",
      "eligible_year": 1998,
      "wait_years": 28,
      "criteria_score": 39.9,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Thin Lizzy",
      "genre": "Heavy Metal",
      "eligible_year": 1996,
      "wait_years": 30,
      "criteria_score": 39.2,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Scorpions",
      "genre": "Heavy Metal",
      "eligible_year": 1997,
      "wait_years": 29,
      "criteria_score": 39.2,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Townes Van Zandt",
      "genre": "Folk/Country",
      "eligible_year": 1993,
      "wait_years": 33,
      "criteria_score": 39.2,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Emmylou Harris",
      "genre": "Folk/Country",
      "eligible_year": 1994,
      "wait_years": 32,
      "criteria_score": 39.2,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Rick James",
      "genre": "Soul/R&B",
      "eligible_year": 2003,
      "wait_years": 23,
      "criteria_score": 39.0,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Joy Division",
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "criteria_score": 38.85,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Emerson Lake & Palmer",
      "genre": "Classic Rock",
      "eligible_year": 1995,
      "wait_years": 31,
      "criteria_score": 38.8,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Bjork",
      "genre": "Electronic",
      "eligible_year": 2002,
      "wait_years": 24,
      "criteria_score": 38.6,
      "verdict": "BORDERLINE"
    },
    {
      "name": "The Damned",
      "genre": "Punk",
      "eligible_year": 2001,
      "wait_years": 25,
      "criteria_score": 38.2,
      "verdict": "BORDERLINE"
    },
    {
      "name": "Motorhead",
      "genre": "Heavy Metal",
      "eligible_year": 2002,
      "wait_years": 24,
      "criteria_score": 37.9,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Wire",
      "genre": "Punk",
      "eligible_year": 2002,
      "wait_years": 24,
      "criteria_score": 37.9,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "The Misfits",
      "genre": "Punk",
      "eligible_year": 2002,
      "wait_years": 24,
      "criteria_score": 37.9,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Styx",
      "genre": "Classic Rock",
      "eligible_year": 1997,
      "wait_years": 29,
      "criteria_score": 37.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "REO Speedwagon",
      "genre": "Classic Rock",
      "eligible_year": 1996,
      "wait_years": 30,
      "criteria_score": 37.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Teena Marie",
      "genre": "Soul/R&B",
      "eligible_year": 2004,
      "wait_years": 22,
      "criteria_score": 37.7,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Siouxsie and the Banshees",
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "criteria_score": 37.6,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "The Fall",
      "genre": "Punk",
      "eligible_year": 2003,
      "wait_years": 23,
      "criteria_score": 37.6,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Boston",
      "genre": "Classic Rock",
      "eligible_year": 2001,
      "wait_years": 25,
      "criteria_score": 36.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "John Prine",
      "genre": "Folk/Country",
      "eligible_year": 1996,
      "wait_years": 30,
      "criteria_score": 36.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "KC and the Sunshine Band",
      "genre": "Disco/Dance",
      "eligible_year": 1998,
      "wait_years": 28,
      "criteria_score": 36.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "The Pointer Sisters",
      "genre": "Disco/Dance",
      "eligible_year": 1998,
      "wait_years": 28,
      "criteria_score": 36.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Dead Kennedys",
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "criteria_score": 36.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Bauhaus",
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "criteria_score": 36.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Descendents",
      "genre": "Punk",
      "eligible_year": 2004,
      "wait_years": 22,
      "criteria_score": 36.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "New Order",
      "genre": "Electronic",
      "eligible_year": 2006,
      "wait_years": 20,
      "criteria_score": 35.1,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Chic",
      "genre": "Disco/Dance",
      "eligible_year": 2002,
      "wait_years": 24,
      "criteria_score": 35.1,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Oingo Boingo",
      "genre": "Classic Rock",
      "eligible_year": 2004,
      "wait_years": 22,
      "criteria_score": 34.9,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Luther Vandross",
      "genre": "Soul/R&B",
      "eligible_year": 2006,
      "wait_years": 20,
      "criteria_score": 34.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Lucinda Williams",
      "genre": "Folk/Country",
      "eligible_year": 2004,
      "wait_years": 22,
      "criteria_score": 33.5,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Mission of Burma",
      "genre": "Punk",
      "eligible_year": 2006,
      "wait_years": 20,
      "criteria_score": 33.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "The Replacements",
      "genre": "Punk",
      "eligible_year": 2006,
      "wait_years": 20,
      "criteria_score": 33.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Husker Du",
      "genre": "Punk",
      "eligible_year": 2006,
      "wait_years": 20,
      "criteria_score": 33.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Minor Threat",
      "genre": "Punk",
      "eligible_year": 2006,
      "wait_years": 20,
      "criteria_score": 33.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Social Distortion",
      "genre": "Punk",
      "eligible_year": 2006,
      "wait_years": 20,
      "criteria_score": 33.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Bad Brains",
      "genre": "Punk",
      "eligible_year": 2007,
      "wait_years": 19,
      "criteria_score": 33.0,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Sonic Youth",
      "genre": "Punk",
      "eligible_year": 2007,
      "wait_years": 19,
      "criteria_score": 33.0,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "New Edition",
      "genre": "Soul/R&B",
      "eligible_year": 2008,
      "wait_years": 18,
      "criteria_score": 32.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Anita Baker",
      "genre": "Soul/R&B",
      "eligible_year": 2008,
      "wait_years": 18,
      "criteria_score": 32.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Sade",
      "genre": "Soul/R&B",
      "eligible_year": 2009,
      "wait_years": 17,
      "criteria_score": 32.5,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Pantera",
      "genre": "Heavy Metal",
      "eligible_year": 2008,
      "wait_years": 18,
      "criteria_score": 31.7,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Slayer",
      "genre": "Heavy Metal",
      "eligible_year": 2008,
      "wait_years": 18,
      "criteria_score": 31.7,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Dio",
      "genre": "Heavy Metal",
      "eligible_year": 2008,
      "wait_years": 18,
      "criteria_score": 31.7,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Queensryche",
      "genre": "Heavy Metal",
      "eligible_year": 2008,
      "wait_years": 18,
      "criteria_score": 31.7,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "LL Cool J",
      "genre": "Hip-Hop",
      "eligible_year": 2010,
      "wait_years": 16,
      "criteria_score": 31.65,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Anthrax",
      "genre": "Heavy Metal",
      "eligible_year": 2009,
      "wait_years": 17,
      "criteria_score": 31.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Salt-N-Pepa",
      "genre": "Hip-Hop",
      "eligible_year": 2011,
      "wait_years": 15,
      "criteria_score": 31.35,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Megadeth",
      "genre": "Heavy Metal",
      "eligible_year": 2010,
      "wait_years": 16,
      "criteria_score": 31.1,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Dinosaur Jr.",
      "genre": "Punk",
      "eligible_year": 2010,
      "wait_years": 16,
      "criteria_score": 31.1,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Sepultura",
      "genre": "Heavy Metal",
      "eligible_year": 2011,
      "wait_years": 15,
      "criteria_score": 30.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "King Diamond",
      "genre": "Heavy Metal",
      "eligible_year": 2011,
      "wait_years": 15,
      "criteria_score": 30.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "The Smiths",
      "genre": "Classic Rock",
      "eligible_year": 2009,
      "wait_years": 17,
      "criteria_score": 30.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Massive Attack",
      "genre": "Electronic",
      "eligible_year": 2013,
      "wait_years": 13,
      "criteria_score": 29.75,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Underworld",
      "genre": "Electronic",
      "eligible_year": 2013,
      "wait_years": 13,
      "criteria_score": 29.75,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "White Zombie",
      "genre": "Heavy Metal",
      "eligible_year": 2012,
      "wait_years": 14,
      "criteria_score": 29.5,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Pixies",
      "genre": "Punk",
      "eligible_year": 2012,
      "wait_years": 14,
      "criteria_score": 29.5,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "De La Soul",
      "genre": "Hip-Hop",
      "eligible_year": 2014,
      "wait_years": 12,
      "criteria_score": 29.45,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Soundgarden",
      "genre": "Heavy Metal",
      "eligible_year": 2013,
      "wait_years": 13,
      "criteria_score": 29.2,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Fugazi",
      "genre": "Punk",
      "eligible_year": 2013,
      "wait_years": 13,
      "criteria_score": 29.2,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Dream Theater",
      "genre": "Heavy Metal",
      "eligible_year": 2014,
      "wait_years": 12,
      "criteria_score": 28.9,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Jane's Addiction",
      "genre": "Classic Rock",
      "eligible_year": 2012,
      "wait_years": 14,
      "criteria_score": 28.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Phish",
      "genre": "Classic Rock",
      "eligible_year": 2013,
      "wait_years": 13,
      "criteria_score": 28.1,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Toad the Wet Sprocket",
      "genre": "Classic Rock",
      "eligible_year": 2014,
      "wait_years": 12,
      "criteria_score": 27.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Ice Cube",
      "genre": "Hip-Hop",
      "eligible_year": 2015,
      "wait_years": 11,
      "criteria_score": 26.6,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Sinead O'Connor",
      "genre": "Pop",
      "eligible_year": 2012,
      "wait_years": 14,
      "criteria_score": 26.2,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Boyz II Men",
      "genre": "Soul/R&B",
      "eligible_year": 2016,
      "wait_years": 10,
      "criteria_score": 25.7,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "TLC",
      "genre": "Soul/R&B",
      "eligible_year": 2017,
      "wait_years": 9,
      "criteria_score": 25.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "The Prodigy",
      "genre": "Electronic",
      "eligible_year": 2016,
      "wait_years": 10,
      "criteria_score": 25.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Cypress Hill",
      "genre": "Hip-Hop",
      "eligible_year": 2016,
      "wait_years": 10,
      "criteria_score": 25.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Aphex Twin",
      "genre": "Electronic",
      "eligible_year": 2017,
      "wait_years": 9,
      "criteria_score": 25.0,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "The Chemical Brothers",
      "genre": "Electronic",
      "eligible_year": 2017,
      "wait_years": 9,
      "criteria_score": 25.0,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Type O Negative",
      "genre": "Heavy Metal",
      "eligible_year": 2016,
      "wait_years": 10,
      "criteria_score": 24.9,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Wu-Tang Clan",
      "genre": "Hip-Hop",
      "eligible_year": 2018,
      "wait_years": 8,
      "criteria_score": 24.7,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Snoop Dogg",
      "genre": "Hip-Hop",
      "eligible_year": 2018,
      "wait_years": 8,
      "criteria_score": 24.7,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Portishead",
      "genre": "Electronic",
      "eligible_year": 2019,
      "wait_years": 7,
      "criteria_score": 24.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Daft Punk",
      "genre": "Electronic",
      "eligible_year": 2019,
      "wait_years": 7,
      "criteria_score": 24.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "OutKast",
      "genre": "Hip-Hop",
      "eligible_year": 2019,
      "wait_years": 7,
      "criteria_score": 24.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Nas",
      "genre": "Hip-Hop",
      "eligible_year": 2019,
      "wait_years": 7,
      "criteria_score": 24.4,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Tool",
      "genre": "Heavy Metal",
      "eligible_year": 2018,
      "wait_years": 8,
      "criteria_score": 24.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Mariah Carey",
      "genre": "Pop",
      "eligible_year": 2015,
      "wait_years": 11,
      "criteria_score": 23.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "D'Angelo",
      "genre": "Soul/R&B",
      "eligible_year": 2020,
      "wait_years": 6,
      "criteria_score": 23.5,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "The Cranberries",
      "genre": "Classic Rock",
      "eligible_year": 2018,
      "wait_years": 8,
      "criteria_score": 23.5,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Erykah Badu",
      "genre": "Soul/R&B",
      "eligible_year": 2022,
      "wait_years": 4,
      "criteria_score": 22.9,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Busta Rhymes",
      "genre": "Hip-Hop",
      "eligible_year": 2021,
      "wait_years": 5,
      "criteria_score": 22.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Lauryn Hill",
      "genre": "Hip-Hop",
      "eligible_year": 2023,
      "wait_years": 3,
      "criteria_score": 22.2,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "DMX",
      "genre": "Hip-Hop",
      "eligible_year": 2023,
      "wait_years": 3,
      "criteria_score": 22.2,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "No Doubt",
      "genre": "Pop",
      "eligible_year": 2017,
      "wait_years": 9,
      "criteria_score": 22.2,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "System of a Down",
      "genre": "Heavy Metal",
      "eligible_year": 2023,
      "wait_years": 3,
      "criteria_score": 21.8,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Lil Wayne",
      "genre": "Hip-Hop",
      "eligible_year": 2024,
      "wait_years": 2,
      "criteria_score": 20.9,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Kanye West",
      "genre": "Hip-Hop",
      "eligible_year": 2026,
      "wait_years": 0,
      "criteria_score": 20.3,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Mastodon",
      "genre": "Heavy Metal",
      "eligible_year": 2025,
      "wait_years": 1,
      "criteria_score": 20.2,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Lamb of God",
      "genre": "Heavy Metal",
      "eligible_year": 2025,
      "wait_years": 1,
      "criteria_score": 20.2,
      "verdict": "INSUFFICIENT"
    },
    {
      "name": "Backstreet Boys",
      "genre": "Pop",
      "eligible_year": 2021,
      "wait_years": 5,
      "criteria_score": 20.0,
      "verdict": "INSUFFICIENT"
    }
  ],
  "genre_colors": {
    "Classic Rock": "#d4a017",
    "Soul/R&B": "#b03434",
    "Pop": "#c47a3a",
    "Folk/Country": "#8a7d48",
    "Hip-Hop": "#5a6f8a",
    "Heavy Metal": "#3d4a5c",
    "Punk": "#7a4a8a",
    "Electronic": "#5f7d56",
    "Blues/Early": "#5c3a2a",
    "Disco/Dance": "#8a5a6f"
  },
  "current_year": 2026,
  "total_eligible": 113,
  "inducted_median_score": 42.0,
  "percentiles": {
    "p25": 38.12,
    "p50": 42.0,
    "p75": 48.65
  },
  "metadata": {
    "source": "Criteria Compliance Model v1",
    "verdict_method": "Based on criteria score percentiles relative to inducted artists"
  }
};
