// One Long Impersonation -- Chapter 05: The Docket
// Client-side search, filter, and sort for the artist docket.
// Reads from window.DOCKET_DATA (generated by pipeline)

(function() {
  'use strict';

  var data = window.DOCKET_DATA;
  if (!data) {
    console.error('[docket-engine] No data found. Run pipeline export first.');
    return;
  }

  var artists = data.artists || [];
  var genreColors = data.genre_colors || {};
  var currentYear = data.current_year || 2026;

  // State
  var filters = {
    text: '',
    genre: '',
    verdict: '',
    sort: 'name'
  };

  // -------------------------------------------------------
  // Filter and sort
  // -------------------------------------------------------
  function applyFilters() {
    var filtered = artists.filter(function(a) {
      if (filters.text && a.name.toLowerCase().indexOf(filters.text.toLowerCase()) === -1) return false;
      if (filters.genre && a.genre !== filters.genre) return false;
      if (filters.verdict && a.verdict !== filters.verdict) return false;
      return true;
    });

    // Sort
    filtered.sort(function(a, b) {
      switch (filters.sort) {
        case 'eligible_year':
          return (a.eligible_year || 9999) - (b.eligible_year || 9999);
        case 'wait_years':
          return (b.wait_years || 0) - (a.wait_years || 0);
        case 'criteria_score':
          return (b.criteria_score || 0) - (a.criteria_score || 0);
        default:
          return a.name.localeCompare(b.name);
      }
    });

    return filtered;
  }

  // -------------------------------------------------------
  // Render table
  // -------------------------------------------------------
  function renderTable() {
    var container = document.getElementById('docket-table');
    var countEl = document.getElementById('docket-count');
    if (!container) return;

    var filtered = applyFilters();

    // Count
    if (countEl) {
      countEl.textContent = filtered.length + ' of ' + artists.length + ' eligible artists';
    }

    // Clear
    container.innerHTML = '';

    // Header
    var header = document.createElement('div');
    header.className = 'docket-header';
    header.innerHTML =
      '<span>Artist</span>' +
      '<span>Genre</span>' +
      '<span>Eligible</span>' +
      '<span>Waiting</span>' +
      '<span>Verdict</span>';
    container.appendChild(header);

    // Rows
    filtered.forEach(function(a) {
      var row = document.createElement('div');
      row.className = 'docket-row';

      var genreColor = genreColors[a.genre] || '#8a8aa3';
      var waitYears = a.wait_years || (currentYear - (a.eligible_year || currentYear));

      var verdictClass = 'verdict--insufficient';
      var verdictLabel = 'Insufficient';
      if (a.verdict === 'STRONG_CASE') { verdictClass = 'verdict--strong'; verdictLabel = 'Strong Case'; }
      else if (a.verdict === 'CASE') { verdictClass = 'verdict--case'; verdictLabel = 'Case'; }
      else if (a.verdict === 'BORDERLINE') { verdictClass = 'verdict--borderline'; verdictLabel = 'Borderline'; }

      row.innerHTML =
        '<div class="docket-row__name">' + a.name + '</div>' +
        '<div class="docket-row__genre" style="color:' + genreColor + '">' + (a.genre || '--') + '</div>' +
        '<div class="docket-row__year">' + (a.eligible_year || '--') + '</div>' +
        '<div class="docket-row__wait">' + waitYears + 'y</div>' +
        '<div class="docket-row__verdict ' + verdictClass + '">' + verdictLabel + '</div>';

      // Expandable criteria breakdown
      if (a.scores) {
        row.style.cursor = 'pointer';
        var detail = document.createElement('div');
        detail.className = 'docket-detail';
        detail.style.display = 'none';

        var criteria = [
          { label: 'Career Length', score: a.scores.career, weight: '15%' },
          { label: 'Catalog Depth', score: a.scores.catalog, weight: '15%' },
          { label: 'Genre Contribution', score: a.scores.contribution, weight: '20%' },
          { label: 'Musical Excellence', score: a.scores.excellence, weight: '25%', sparse: true },
          { label: 'Influence', score: a.scores.influence, weight: '25%', sparse: true }
        ];

        var detailHtml = '<div class="docket-detail__grid">';
        criteria.forEach(function(c) {
          var pct = Math.round(c.score || 0);
          var noData = c.sparse && pct === 0;
          var barColor = pct >= 60 ? '#5f7d56' : pct >= 30 ? '#d4a017' : '#b03434';
          detailHtml +=
            '<div class="docket-detail__item">' +
              '<span class="docket-detail__label">' + c.label + ' <span style="opacity:0.4">(' + c.weight + ')</span></span>';
          if (noData) {
            detailHtml +=
              '<div class="docket-detail__bar-bg"><div class="docket-detail__bar-fill" style="width:100%; background:var(--rule); opacity:0.3"></div></div>' +
              '<span class="docket-detail__score" style="color:var(--mute); font-size:10px">Awaiting data</span>';
          } else {
            detailHtml +=
              '<div class="docket-detail__bar-bg"><div class="docket-detail__bar-fill" style="width:' + pct + '%; background:' + barColor + '"></div></div>' +
              '<span class="docket-detail__score">' + pct + '</span>';
          }
          detailHtml += '</div>';
        });
        detailHtml += '</div>';
        detailHtml += '<p class="docket-detail__caveat">Career, Catalog, and Genre Contribution scores are computed from documented data. Musical Excellence and Influence scores require RS coverage and influence graph data not yet fully ingested for all eligible artists.</p>';
        detail.innerHTML = detailHtml;

        row.addEventListener('click', function() {
          var showing = detail.style.display !== 'none';
          detail.style.display = showing ? 'none' : 'block';
          row.classList.toggle('docket-row--expanded', !showing);
        });

        container.appendChild(row);
        container.appendChild(detail);
      } else {
        container.appendChild(row);
      }
    });
  }

  // -------------------------------------------------------
  // Bind controls
  // -------------------------------------------------------
  function bindControls() {
    var textInput = document.getElementById('docket-filter');
    var genreSelect = document.getElementById('filter-genre');
    var verdictSelect = document.getElementById('filter-verdict');
    var sortSelect = document.getElementById('sort-by');

    if (textInput) {
      textInput.addEventListener('input', function() {
        filters.text = this.value;
        renderTable();
      });
    }
    if (genreSelect) {
      genreSelect.addEventListener('change', function() {
        filters.genre = this.value;
        renderTable();
      });
    }
    if (verdictSelect) {
      verdictSelect.addEventListener('change', function() {
        filters.verdict = this.value;
        renderTable();
      });
    }
    if (sortSelect) {
      sortSelect.addEventListener('change', function() {
        filters.sort = this.value;
        renderTable();
      });
    }
  }

  // -------------------------------------------------------
  // Initialize
  // -------------------------------------------------------
  function init() {
    bindControls();
    renderTable();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
