// One Long Impersonation -- Chapter 04: The Rolling Stone Connection
// D3 visualization engine for Wenner Coefficient exhibits
// Reads from window.WENNER_DATA (generated by pipeline)

(function() {
  'use strict';

  var data = window.WENNER_DATA;
  if (!data) {
    console.error('[wenner-engine] No data found. Run pipeline first.');
    return;
  }

  // Design tokens (fallbacks matching design-tokens.css)
  var COLORS = {
    ink:       '#14142b',
    ink2:      '#1d1d3a',
    cream:     '#efe8d6',
    cream2:    '#d8cfb6',
    gold:      '#d4a017',
    goldHot:   '#e8b727',
    blood:     '#b03434',
    bloodDeep: '#7a1f1f',
    moss:      '#5f7d56',
    mute:      '#8a8aa3',
    rule:      '#2e2e55',
    paper:     '#f1ece1',
    bone:      '#f6f2ea'
  };

  var GENRE_COLORS = {
    'Classic Rock': '#d4a017',
    'Soul/R&B':     '#b03434',
    'Pop':          '#c47a3a',
    'Folk/Country': '#8a7d48',
    'Hip-Hop':      '#5a6f8a',
    'Heavy Metal':  '#3d4a5c',
    'Punk':         '#7a4a8a',
    'Electronic':   '#5f7d56',
    'Blues/Early':   '#5c3a2a',
    'Disco/Dance':  '#8a5a6f'
  };

  // -------------------------------------------------------
  // Crosshair corner ticks (forensic exhibit framing)
  // -------------------------------------------------------
  function drawCrosshairs(svg, width, height, color) {
    var tickLen = 12;
    var tickStroke = color || 'rgba(212,160,23,0.4)';
    var off = 4;

    var corners = [
      { x1: off, y1: off, dx: tickLen, dy: 0 },
      { x1: off, y1: off, dx: 0, dy: tickLen },
      { x1: width - off, y1: off, dx: -tickLen, dy: 0 },
      { x1: width - off, y1: off, dx: 0, dy: tickLen },
      { x1: off, y1: height - off, dx: tickLen, dy: 0 },
      { x1: off, y1: height - off, dx: 0, dy: -tickLen },
      { x1: width - off, y1: height - off, dx: -tickLen, dy: 0 },
      { x1: width - off, y1: height - off, dx: 0, dy: -tickLen }
    ];

    corners.forEach(function(c) {
      svg.append('line')
        .attr('x1', c.x1).attr('y1', c.y1)
        .attr('x2', c.x1 + c.dx).attr('y2', c.y1 + c.dy)
        .attr('stroke', tickStroke)
        .attr('stroke-width', 1);
    });
  }

  // -------------------------------------------------------
  // HEADLINE STATISTICS
  // -------------------------------------------------------
  function renderStats() {
    var wc = data.wenner_coefficient;

    var el;
    el = document.getElementById('stat-wait-with');
    if (el) el.textContent = wc.median_wait_with_rs + 'y';

    el = document.getElementById('stat-wait-without');
    if (el) el.textContent = wc.median_wait_without_rs + 'y';

    el = document.getElementById('stat-rho');
    if (el) el.textContent = wc.spearman_rho.toFixed(2);

    el = document.getElementById('stat-n-with');
    if (el) el.textContent = wc.n_with_rs;

    el = document.getElementById('stat-n-without');
    if (el) el.textContent = wc.n_without_rs;

    el = document.getElementById('stat-pearson');
    if (el) el.textContent = wc.pearson_r.toFixed(2);

    el = document.getElementById('caveat-rho');
    if (el) el.textContent = wc.spearman_rho.toFixed(2);
  }

  // -------------------------------------------------------
  // Ex. 004-A: SCATTER PLOT (RS Attention Score vs Wait Time)
  // -------------------------------------------------------
  function renderScatter() {
    var container = document.getElementById('scatter-chart');
    if (!container) return;

    var scatter = data.scatter_data;

    // Dimensions
    var margin = { top: 48, right: 48, bottom: 72, left: 64 };
    var width = Math.max(container.clientWidth, 700);
    var height = 560;
    var plotW = width - margin.left - margin.right;
    var plotH = height - margin.top - margin.bottom;

    // Scales
    var xMax = d3.max(scatter, function(d) { return d.rs_score; });
    var yMax = d3.max(scatter, function(d) { return d.wait_time; });

    var x = d3.scaleLinear()
      .domain([0, Math.ceil(xMax / 10) * 10])
      .range([0, plotW]);

    var y = d3.scaleLinear()
      .domain([0, Math.ceil(yMax / 5) * 5])
      .range([plotH, 0]);

    // Create SVG
    var svg = d3.select(container)
      .append('svg')
      .attr('width', width)
      .attr('height', height)
      .attr('viewBox', '0 0 ' + width + ' ' + height)
      .attr('role', 'img')
      .attr('aria-label', 'Scatter plot: RS Attention Score (x-axis) vs induction wait time in years (y-axis), colored by genre');

    // Background
    svg.append('rect')
      .attr('width', width)
      .attr('height', height)
      .attr('fill', COLORS.ink2);

    drawCrosshairs(svg, width, height);

    var g = svg.append('g')
      .attr('transform', 'translate(' + margin.left + ',' + margin.top + ')');

    // Grid lines
    var xTicks = x.ticks(10);
    var yTicks = y.ticks(8);

    xTicks.forEach(function(v) {
      g.append('line')
        .attr('x1', x(v)).attr('x2', x(v))
        .attr('y1', 0).attr('y2', plotH)
        .attr('stroke', COLORS.rule)
        .attr('stroke-width', 1)
        .attr('opacity', 0.5);
    });

    yTicks.forEach(function(v) {
      g.append('line')
        .attr('x1', 0).attr('x2', plotW)
        .attr('y1', y(v)).attr('y2', y(v))
        .attr('stroke', COLORS.rule)
        .attr('stroke-width', 1)
        .attr('opacity', 0.5);
    });

    // Axes labels
    xTicks.forEach(function(v) {
      g.append('text')
        .attr('x', x(v))
        .attr('y', plotH + 24)
        .attr('text-anchor', 'middle')
        .attr('fill', COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 10)
        .text(v);
    });

    yTicks.forEach(function(v) {
      g.append('text')
        .attr('x', -12)
        .attr('y', y(v) + 4)
        .attr('text-anchor', 'end')
        .attr('fill', COLORS.mute)
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 10)
        .text(v);
    });

    // Axis titles
    g.append('text')
      .attr('x', plotW / 2)
      .attr('y', plotH + 52)
      .attr('text-anchor', 'middle')
      .attr('fill', COLORS.cream2)
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 11)
      .attr('letter-spacing', '0.1em')
      .text('RS ATTENTION SCORE');

    g.append('text')
      .attr('transform', 'rotate(-90)')
      .attr('x', -plotH / 2)
      .attr('y', -48)
      .attr('text-anchor', 'middle')
      .attr('fill', COLORS.cream2)
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 11)
      .attr('letter-spacing', '0.1em')
      .text('WAIT TIME (YEARS)');

    // ---- TREND LINE ----
    // Linear regression for trend line
    var sumX = 0, sumY = 0, sumXY = 0, sumXX = 0, n = scatter.length;
    scatter.forEach(function(d) {
      sumX += d.rs_score;
      sumY += d.wait_time;
      sumXY += d.rs_score * d.wait_time;
      sumXX += d.rs_score * d.rs_score;
    });
    var slope = (n * sumXY - sumX * sumY) / (n * sumXX - sumX * sumX);
    var intercept = (sumY - slope * sumX) / n;

    var trendX1 = 0;
    var trendX2 = xMax;
    var trendY1 = Math.max(0, intercept);
    var trendY2 = Math.max(0, intercept + slope * trendX2);

    g.append('line')
      .attr('x1', x(trendX1))
      .attr('y1', y(trendY1))
      .attr('x2', x(trendX2))
      .attr('y2', y(trendY2))
      .attr('stroke', COLORS.gold)
      .attr('stroke-width', 2)
      .attr('stroke-dasharray', '8,4')
      .attr('opacity', 0.7);

    // Trend line label
    g.append('text')
      .attr('x', x(trendX2) + 6)
      .attr('y', y(trendY2) + 4)
      .attr('fill', COLORS.gold)
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 9)
      .attr('font-weight', 600)
      .text('TREND');

    // ---- DOTS ----
    // Sort so that dots with higher rs_score render on top (they are fewer, more interesting)
    var sorted = scatter.slice().sort(function(a, b) { return a.rs_score - b.rs_score; });

    // Shape encoding by genre group for accessibility (not color-only)
    var GENRE_SHAPES = {
      'Classic Rock': 'circle', 'Soul/R&B': 'square', 'Pop': 'diamond',
      'Folk/Country': 'triangle', 'Hip-Hop': 'cross', 'Heavy Metal': 'star',
      'Punk': 'triangle', 'Electronic': 'square', 'Blues/Early': 'diamond',
      'Disco/Dance': 'cross'
    };

    function drawShape(g, cx, cy, shape, size, fill, opacity) {
      var s = size;
      if (shape === 'square') {
        g.append('rect').attr('x', cx-s).attr('y', cy-s).attr('width', s*2).attr('height', s*2)
          .attr('fill', fill).attr('opacity', opacity);
      } else if (shape === 'diamond') {
        g.append('polygon').attr('points', cx+','+( cy-s)+' '+(cx+s)+','+cy+' '+cx+','+(cy+s)+' '+(cx-s)+','+cy)
          .attr('fill', fill).attr('opacity', opacity);
      } else if (shape === 'triangle') {
        g.append('polygon').attr('points', cx+','+(cy-s)+' '+(cx+s)+','+(cy+s)+' '+(cx-s)+','+(cy+s))
          .attr('fill', fill).attr('opacity', opacity);
      } else if (shape === 'cross') {
        g.append('line').attr('x1',cx-s).attr('y1',cy).attr('x2',cx+s).attr('y2',cy).attr('stroke',fill).attr('stroke-width',2).attr('opacity',opacity);
        g.append('line').attr('x1',cx).attr('y1',cy-s).attr('x2',cx).attr('y2',cy+s).attr('stroke',fill).attr('stroke-width',2).attr('opacity',opacity);
      } else {
        g.append('circle').attr('cx', cx).attr('cy', cy).attr('r', s)
          .attr('fill', fill).attr('opacity', opacity);
      }
    }

    sorted.forEach(function(d) {
      var color = GENRE_COLORS[d.genre] || COLORS.mute;
      var isZero = d.rs_score === 0;
      var shape = GENRE_SHAPES[d.genre] || 'circle';

      drawShape(g, x(d.rs_score), y(d.wait_time), shape,
                isZero ? 3 : 5, color, isZero ? 0.35 : 0.88);
    });

    // ---- OUTLIER LABELS ----
    var outliers = [
      { name: 'The Beatles',   anchor: 'start',  dx: 8,   dy: -8  },
      { name: 'Nina Simone',   anchor: 'start',  dx: 8,   dy: -6  },
      { name: 'Dolly Parton',  anchor: 'start',  dx: 8,   dy: -6  },
      { name: 'Iron Maiden',   anchor: 'start',  dx: 8,   dy: 4   },
      { name: 'Willie Nelson', anchor: 'end',    dx: -8,  dy: -6  },
      { name: 'Kate Bush',     anchor: 'start',  dx: 8,   dy: -6  },
      { name: 'Nirvana',       anchor: 'start',  dx: 8,   dy: 12  },
      { name: 'Cher',          anchor: 'end',    dx: -8,  dy: -6  }
    ];

    var nameMap = {};
    scatter.forEach(function(d) { nameMap[d.name] = d; });

    outliers.forEach(function(o) {
      var d = nameMap[o.name];
      if (!d) return;

      g.append('text')
        .attr('x', x(d.rs_score) + o.dx)
        .attr('y', y(d.wait_time) + o.dy)
        .attr('text-anchor', o.anchor)
        .attr('fill', COLORS.cream)
        .attr('font-family', '"Inter", sans-serif')
        .attr('font-size', 10)
        .attr('font-weight', 500)
        .text(o.name);
    });

    // ---- LEGEND ----
    var legendDiv = document.createElement('div');
    legendDiv.className = 'scatter-legend';

    var genres = Object.keys(GENRE_COLORS);
    genres.forEach(function(genre) {
      var item = document.createElement('span');
      item.className = 'scatter-legend__item';

      var dot = document.createElement('span');
      dot.className = 'scatter-legend__dot';
      dot.style.background = GENRE_COLORS[genre];
      item.appendChild(dot);

      var label = document.createTextNode(genre);
      item.appendChild(label);
      legendDiv.appendChild(item);
    });

    container.appendChild(legendDiv);
  }

  // -------------------------------------------------------
  // COMMITTEE TIMELINE + WENNER QUOTES
  // -------------------------------------------------------
  function renderCommittee() {
    var timelineEl = document.getElementById('committee-timeline');
    var quotesEl = document.getElementById('wenner-quotes-block');
    if (!timelineEl || !quotesEl) return;

    var committee = data.committee;

    // Timeline rows
    var tenure = committee.wenner_tenure;
    var connections = committee.documented_rs_connections;

    var timelineHTML = '';

    // Wenner tenure phases
    timelineHTML +=
      '<div class="committee-row">' +
        '<div class="committee-row__years">1986 -- 2006</div>' +
        '<div>' +
          '<div class="committee-row__role">Jann Wenner serves on the nominating committee</div>' +
          '<div class="committee-row__source">Source: Rock Hall Foundation public records</div>' +
        '</div>' +
      '</div>';

    timelineHTML +=
      '<div class="committee-row">' +
        '<div class="committee-row__years">2006 -- 2019</div>' +
        '<div>' +
          '<div class="committee-row__role">Jann Wenner serves as Chairman, Rock Hall Foundation</div>' +
          '<div class="committee-row__source">Source: Rock Hall Foundation public records</div>' +
        '</div>' +
      '</div>';

    timelineHTML +=
      '<div class="committee-row">' +
        '<div class="committee-row__years">2020 -- present</div>' +
        '<div>' +
          '<div class="committee-row__role">John Sykes serves as Chairman (post-Wenner)</div>' +
          '<div class="committee-row__source">Source: Rock Hall Foundation announcement, 2019</div>' +
        '</div>' +
      '</div>';

    timelineHTML +=
      '<div class="committee-row">' +
        '<div class="committee-row__years" style="color:var(--blood)">Sept 2023</div>' +
        '<div>' +
          '<div class="committee-row__role">Wenner removed from board of directors</div>' +
          '<div class="committee-row__source">Source: ' + tenure.removal_source + '</div>' +
        '</div>' +
      '</div>';

    timelineEl.innerHTML = timelineHTML;

    // Wenner quotes
    var q2023 = committee.wenner_quote_2023;
    var q2022 = committee.wenner_quote_2022;

    var quotesHTML = '';

    quotesHTML +=
      '<div class="wenner-quote">' +
        '<p class="wenner-quote__text">"' + q2023.quote + '"</p>' +
        '<p class="wenner-quote__context">' + q2023.context + '</p>' +
        '<p class="wenner-quote__source">' + q2023.source + '</p>' +
      '</div>';

    quotesHTML +=
      '<div class="wenner-quote">' +
        '<p class="wenner-quote__text">"' + q2022.quote + '"</p>' +
        '<p class="wenner-quote__context">' + q2022.context + '</p>' +
        '<p class="wenner-quote__source">' + q2022.source + '</p>' +
      '</div>';

    quotesHTML +=
      '<p style="font-size:12px; color:var(--mute); margin-top:24px; line-height:1.6" class="mono">' +
        committee.note +
      '</p>';

    quotesEl.innerHTML = quotesHTML;
  }

  // -------------------------------------------------------
  // Initialize
  // -------------------------------------------------------
  function init() {
    renderStats();
    renderScatter();
    renderCommittee();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
