// One Long Impersonation -- Chapter 04: The Rolling Stone Connection
// Wenner Coefficient data -- generated by pipeline
// CORRELATION, NOT CAUSATION. The chapter says so explicitly.

window.WENNER_DATA = {
  "wenner_coefficient": {
    "pearson_r": -0.3751,
    "pearson_p": 5.61e-10,
    "spearman_rho": -0.4326,
    "spearman_p": 4.24e-13,
    "n_with_rs": 76,
    "n_without_rs": 180,
    "median_wait_with_rs": 4.0,
    "median_wait_without_rs": 13.0,
    "mean_wait_with_rs": 6.2,
    "mean_wait_without_rs": 13.5
  },
  "scatter_data": [
    {
      "name": "The Beatles",
      "rs_score": 100.0,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Bob Dylan",
      "rs_score": 88.7,
      "wait_time": 2,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Rolling Stones",
      "rs_score": 87.97,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Prince",
      "rs_score": 86.51,
      "wait_time": 1,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Aretha Franklin",
      "rs_score": 86.06,
      "wait_time": 2,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Stevie Wonder",
      "rs_score": 83.09,
      "wait_time": 2,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Led Zeppelin",
      "rs_score": 82.99,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Marvin Gaye",
      "rs_score": 81.81,
      "wait_time": 1,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Who",
      "rs_score": 73.93,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Bruce Springsteen",
      "rs_score": 73.5,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "David Bowie",
      "rs_score": 68.34,
      "wait_time": 7,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Velvet Underground",
      "rs_score": 65.32,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Elvis Presley",
      "rs_score": 63.59,
      "wait_time": 8,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Jimi Hendrix",
      "rs_score": 62.91,
      "wait_time": 3,
      "genre": "Classic Rock",
      "race": "Black"
    },
    {
      "name": "Chuck Berry",
      "rs_score": 62.51,
      "wait_time": 6,
      "genre": "Classic Rock",
      "race": "Black"
    },
    {
      "name": "B.B. King",
      "rs_score": 62.15,
      "wait_time": 13,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "James Brown",
      "rs_score": 61.73,
      "wait_time": 5,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Little Richard",
      "rs_score": 61.37,
      "wait_time": 10,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Clash",
      "rs_score": 61.05,
      "wait_time": 1,
      "genre": "Punk",
      "race": "white"
    },
    {
      "name": "Nirvana",
      "rs_score": 60.64,
      "wait_time": 0,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Ray Charles",
      "rs_score": 60.52,
      "wait_time": 12,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Joni Mitchell",
      "rs_score": 58.51,
      "wait_time": 5,
      "genre": "Folk/Country",
      "race": "white"
    },
    {
      "name": "Michael Jackson",
      "rs_score": 57.83,
      "wait_time": 5,
      "genre": "Pop",
      "race": "Black"
    },
    {
      "name": "Sam Cooke",
      "rs_score": 57.73,
      "wait_time": 10,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Otis Redding",
      "rs_score": 54.91,
      "wait_time": 2,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Muddy Waters",
      "rs_score": 50.13,
      "wait_time": 21,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "Pink Floyd",
      "rs_score": 47.61,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Neil Young",
      "rs_score": 46.4,
      "wait_time": 2,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Run-D.M.C.",
      "rs_score": 44.89,
      "wait_time": 1,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "Buddy Holly",
      "rs_score": 44.29,
      "wait_time": 5,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Janis Joplin",
      "rs_score": 41.57,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Bo Diddley",
      "rs_score": 40.76,
      "wait_time": 7,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "U2",
      "rs_score": 39.76,
      "wait_time": 0,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Patti Smith",
      "rs_score": 38.42,
      "wait_time": 8,
      "genre": "Punk",
      "race": "white"
    },
    {
      "name": "Radiohead",
      "rs_score": 38.3,
      "wait_time": 2,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Fats Domino",
      "rs_score": 38.25,
      "wait_time": 12,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "Eric Clapton",
      "rs_score": 38.1,
      "wait_time": 12,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Ramones",
      "rs_score": 37.75,
      "wait_time": 1,
      "genre": "Punk",
      "race": "white"
    },
    {
      "name": "AC/DC",
      "rs_score": 35.93,
      "wait_time": 5,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Metallica",
      "rs_score": 35.63,
      "wait_time": 1,
      "genre": "Heavy Metal",
      "race": "white"
    },
    {
      "name": "Johnny Cash",
      "rs_score": 35.23,
      "wait_time": 12,
      "genre": "Folk/Country",
      "race": "white"
    },
    {
      "name": "Black Sabbath",
      "rs_score": 33.22,
      "wait_time": 12,
      "genre": "Heavy Metal",
      "race": "white"
    },
    {
      "name": "Madonna",
      "rs_score": 32.71,
      "wait_time": 1,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "The Doors",
      "rs_score": 30.2,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Van Morrison",
      "rs_score": 29.69,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Sly & The Family Stone",
      "rs_score": 29.19,
      "wait_time": 1,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Jay-Z",
      "rs_score": 28.56,
      "wait_time": 0,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "Whitney Houston",
      "rs_score": 27.45,
      "wait_time": 10,
      "genre": "Pop",
      "race": "Black"
    },
    {
      "name": "Nina Simone",
      "rs_score": 26.72,
      "wait_time": 35,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Elton John",
      "rs_score": 26.17,
      "wait_time": 0,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Beach Boys",
      "rs_score": 25.11,
      "wait_time": 2,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Fleetwood Mac",
      "rs_score": 24.86,
      "wait_time": 6,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Public Enemy",
      "rs_score": 24.36,
      "wait_time": 1,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "The Notorious B.I.G.",
      "rs_score": 23.91,
      "wait_time": 1,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "Pearl Jam",
      "rs_score": 23.65,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Guns N' Roses",
      "rs_score": 22.09,
      "wait_time": 2,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Kate Bush",
      "rs_score": 21.79,
      "wait_time": 20,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "N.W.A",
      "rs_score": 21.04,
      "wait_time": 5,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "Tupac Shakur",
      "rs_score": 19.98,
      "wait_time": 1,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "Eminem",
      "rs_score": 19.02,
      "wait_time": 1,
      "genre": "Hip-Hop",
      "race": "white"
    },
    {
      "name": "Talking Heads",
      "rs_score": 18.62,
      "wait_time": 0,
      "genre": "Punk",
      "race": "white"
    },
    {
      "name": "The Kinks",
      "rs_score": 18.12,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "A Tribe Called Quest",
      "rs_score": 17.46,
      "wait_time": 9,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "Depeche Mode",
      "rs_score": 17.26,
      "wait_time": 14,
      "genre": "Electronic",
      "race": "white"
    },
    {
      "name": "Dolly Parton",
      "rs_score": 17.09,
      "wait_time": 30,
      "genre": "Folk/Country",
      "race": "white"
    },
    {
      "name": "Tina Turner",
      "rs_score": 14.49,
      "wait_time": 12,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Al Green",
      "rs_score": 14.34,
      "wait_time": 3,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Van Halen",
      "rs_score": 14.04,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Smokey Robinson",
      "rs_score": 13.66,
      "wait_time": 5,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Stevie Ray Vaughan",
      "rs_score": 13.44,
      "wait_time": 7,
      "genre": "Blues/Early",
      "race": "white"
    },
    {
      "name": "Santana",
      "rs_score": 12.23,
      "wait_time": 7,
      "genre": "Classic Rock",
      "race": "Latino"
    },
    {
      "name": "Janet Jackson",
      "rs_score": 12.13,
      "wait_time": 12,
      "genre": "Pop",
      "race": "Black"
    },
    {
      "name": "Buddy Guy",
      "rs_score": 10.72,
      "wait_time": 22,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "Missy Elliott",
      "rs_score": 7.85,
      "wait_time": 1,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "Iron Maiden",
      "rs_score": 5.08,
      "wait_time": 21,
      "genre": "Heavy Metal",
      "race": "white"
    },
    {
      "name": "Cyndi Lauper",
      "rs_score": 1.13,
      "wait_time": 17,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "ABBA",
      "rs_score": 0.0,
      "wait_time": 13,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Aerosmith",
      "rs_score": 0.0,
      "wait_time": 3,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Albert King",
      "rs_score": 0.0,
      "wait_time": 35,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "Alice Cooper",
      "rs_score": 0.0,
      "wait_time": 17,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Beastie Boys",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Hip-Hop",
      "race": "white"
    },
    {
      "name": "Bee Gees",
      "rs_score": 0.0,
      "wait_time": 9,
      "genre": "Disco/Dance",
      "race": "white"
    },
    {
      "name": "Big Joe Turner",
      "rs_score": 0.0,
      "wait_time": 24,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "Bill Haley",
      "rs_score": 0.0,
      "wait_time": 11,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Bill Withers",
      "rs_score": 0.0,
      "wait_time": 20,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Billy Joel",
      "rs_score": 0.0,
      "wait_time": 3,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Blondie",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Punk",
      "race": "white"
    },
    {
      "name": "Bob Marley",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Classic Rock",
      "race": "Black"
    },
    {
      "name": "Bob Seger",
      "rs_score": 0.0,
      "wait_time": 13,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Bobby Blue Bland",
      "rs_score": 0.0,
      "wait_time": 15,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "Bobby Darin",
      "rs_score": 0.0,
      "wait_time": 9,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Bobby Womack",
      "rs_score": 0.0,
      "wait_time": 23,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Bon Jovi",
      "rs_score": 0.0,
      "wait_time": 10,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Bonnie Raitt",
      "rs_score": 0.0,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Booker T. & the M.G.'s",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Brenda Lee",
      "rs_score": 0.0,
      "wait_time": 21,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Buffalo Springfield",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Carl Perkins",
      "rs_score": 0.0,
      "wait_time": 8,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Carly Simon",
      "rs_score": 0.0,
      "wait_time": 26,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Carole King",
      "rs_score": 0.0,
      "wait_time": 26,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Cat Stevens",
      "rs_score": 0.0,
      "wait_time": 22,
      "genre": "Folk/Country",
      "race": "white"
    },
    {
      "name": "Cheap Trick",
      "rs_score": 0.0,
      "wait_time": 14,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Cher",
      "rs_score": 0.0,
      "wait_time": 36,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Chicago",
      "rs_score": 0.0,
      "wait_time": 22,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Clyde McPhatter",
      "rs_score": 0.0,
      "wait_time": 12,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Cream",
      "rs_score": 0.0,
      "wait_time": 2,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Creedence Clearwater Revival",
      "rs_score": 0.0,
      "wait_time": 0,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Crosby, Stills & Nash",
      "rs_score": 0.0,
      "wait_time": 3,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Curtis Mayfield",
      "rs_score": 0.0,
      "wait_time": 16,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Darlene Love",
      "rs_score": 0.0,
      "wait_time": 24,
      "genre": "Pop",
      "race": "Black"
    },
    {
      "name": "Dave Matthews Band",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Deep Purple",
      "rs_score": 0.0,
      "wait_time": 23,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Def Leppard",
      "rs_score": 0.0,
      "wait_time": 14,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Del Shannon",
      "rs_score": 0.0,
      "wait_time": 14,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Dion",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Dire Straits",
      "rs_score": 0.0,
      "wait_time": 15,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Donna Summer",
      "rs_score": 0.0,
      "wait_time": 14,
      "genre": "Disco/Dance",
      "race": "Black"
    },
    {
      "name": "Donovan",
      "rs_score": 0.0,
      "wait_time": 22,
      "genre": "Folk/Country",
      "race": "white"
    },
    {
      "name": "Dr. John",
      "rs_score": 0.0,
      "wait_time": 18,
      "genre": "Blues/Early",
      "race": "white"
    },
    {
      "name": "Duane Eddy",
      "rs_score": 0.0,
      "wait_time": 11,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Duran Duran",
      "rs_score": 0.0,
      "wait_time": 16,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Dusty Springfield",
      "rs_score": 0.0,
      "wait_time": 11,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Eagles",
      "rs_score": 0.0,
      "wait_time": 2,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Earth, Wind & Fire",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Eddie Cochran",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Electric Light Orchestra",
      "rs_score": 0.0,
      "wait_time": 21,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Elvis Costello & The Attractions",
      "rs_score": 0.0,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Etta James",
      "rs_score": 0.0,
      "wait_time": 14,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Eurythmics",
      "rs_score": 0.0,
      "wait_time": 17,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Foo Fighters",
      "rs_score": 0.0,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Foreigner",
      "rs_score": 0.0,
      "wait_time": 22,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Frank Zappa",
      "rs_score": 0.0,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Frankie Lymon & The Teenagers",
      "rs_score": 0.0,
      "wait_time": 12,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Gene Pitney",
      "rs_score": 0.0,
      "wait_time": 18,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Gene Vincent",
      "rs_score": 0.0,
      "wait_time": 17,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Genesis",
      "rs_score": 0.0,
      "wait_time": 16,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "George Harrison",
      "rs_score": 0.0,
      "wait_time": 11,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "George Michael",
      "rs_score": 0.0,
      "wait_time": 16,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Gladys Knight & The Pips",
      "rs_score": 0.0,
      "wait_time": 10,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Grandmaster Flash & The Furious Five",
      "rs_score": 0.0,
      "wait_time": 3,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "Green Day",
      "rs_score": 0.0,
      "wait_time": 0,
      "genre": "Punk",
      "race": "white"
    },
    {
      "name": "Hall & Oates",
      "rs_score": 0.0,
      "wait_time": 17,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Hank Ballard",
      "rs_score": 0.0,
      "wait_time": 12,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Heart",
      "rs_score": 0.0,
      "wait_time": 13,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Ike & Tina Turner",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Isaac Hayes",
      "rs_score": 0.0,
      "wait_time": 15,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Jackie Wilson",
      "rs_score": 0.0,
      "wait_time": 9,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Jackson Browne",
      "rs_score": 0.0,
      "wait_time": 7,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Jeff Beck",
      "rs_score": 0.0,
      "wait_time": 18,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Jefferson Airplane",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Jerry Lee Lewis",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Jimmy Cliff",
      "rs_score": 0.0,
      "wait_time": 23,
      "genre": "Classic Rock",
      "race": "Black"
    },
    {
      "name": "Jimmy Reed",
      "rs_score": 0.0,
      "wait_time": 13,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "Joan Baez",
      "rs_score": 0.0,
      "wait_time": 32,
      "genre": "Folk/Country",
      "race": "Latino"
    },
    {
      "name": "Joan Jett & The Blackhearts",
      "rs_score": 0.0,
      "wait_time": 10,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "John Lee Hooker",
      "rs_score": 0.0,
      "wait_time": 18,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "John Lennon",
      "rs_score": 0.0,
      "wait_time": 0,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "John Mellencamp",
      "rs_score": 0.0,
      "wait_time": 7,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Journey",
      "rs_score": 0.0,
      "wait_time": 17,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Kiss",
      "rs_score": 0.0,
      "wait_time": 15,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Kool & The Gang",
      "rs_score": 0.0,
      "wait_time": 30,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "LaVern Baker",
      "rs_score": 0.0,
      "wait_time": 13,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Laura Nyro",
      "rs_score": 0.0,
      "wait_time": 21,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Leonard Cohen",
      "rs_score": 0.0,
      "wait_time": 16,
      "genre": "Folk/Country",
      "race": "white"
    },
    {
      "name": "Linda Ronstadt",
      "rs_score": 0.0,
      "wait_time": 20,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Lionel Richie",
      "rs_score": 0.0,
      "wait_time": 29,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Little Anthony & The Imperials",
      "rs_score": 0.0,
      "wait_time": 27,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Little Willie John",
      "rs_score": 0.0,
      "wait_time": 18,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Lloyd Price",
      "rs_score": 0.0,
      "wait_time": 21,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Lou Reed",
      "rs_score": 0.0,
      "wait_time": 18,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Lynyrd Skynyrd",
      "rs_score": 0.0,
      "wait_time": 8,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Martha & The Vandellas",
      "rs_score": 0.0,
      "wait_time": 8,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Mary J. Blige",
      "rs_score": 0.0,
      "wait_time": 8,
      "genre": "Hip-Hop",
      "race": "Black"
    },
    {
      "name": "Miles Davis",
      "rs_score": 0.0,
      "wait_time": 36,
      "genre": "Blues/Early",
      "race": "Black"
    },
    {
      "name": "Neil Diamond",
      "rs_score": 0.0,
      "wait_time": 20,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Nine Inch Nails",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Electronic",
      "race": "white"
    },
    {
      "name": "Oasis",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Ozzy Osbourne",
      "rs_score": 0.0,
      "wait_time": 29,
      "genre": "Heavy Metal",
      "race": "white"
    },
    {
      "name": "Parliament-Funkadelic",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Pat Benatar",
      "rs_score": 0.0,
      "wait_time": 18,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Paul McCartney",
      "rs_score": 0.0,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Paul Simon",
      "rs_score": 0.0,
      "wait_time": 11,
      "genre": "Folk/Country",
      "race": "white"
    },
    {
      "name": "Percy Sledge",
      "rs_score": 0.0,
      "wait_time": 14,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Peter Frampton",
      "rs_score": 0.0,
      "wait_time": 27,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Peter Gabriel",
      "rs_score": 0.0,
      "wait_time": 12,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Queen",
      "rs_score": 0.0,
      "wait_time": 3,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "R.E.M.",
      "rs_score": 0.0,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Rage Against the Machine",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Heavy Metal",
      "race": "white"
    },
    {
      "name": "Randy Newman",
      "rs_score": 0.0,
      "wait_time": 20,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "Red Hot Chili Peppers",
      "rs_score": 0.0,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Ricky Nelson",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Ringo Starr",
      "rs_score": 0.0,
      "wait_time": 20,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Ritchie Valens",
      "rs_score": 0.0,
      "wait_time": 18,
      "genre": "Classic Rock",
      "race": "Latino"
    },
    {
      "name": "Rod Stewart",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Roxy Music",
      "rs_score": 0.0,
      "wait_time": 22,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Roy Orbison",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Rush",
      "rs_score": 0.0,
      "wait_time": 14,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Ruth Brown",
      "rs_score": 0.0,
      "wait_time": 19,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Sam & Dave",
      "rs_score": 0.0,
      "wait_time": 6,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Sex Pistols",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Punk",
      "race": "white"
    },
    {
      "name": "Sheryl Crow",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Simon & Garfunkel",
      "rs_score": 0.0,
      "wait_time": 1,
      "genre": "Folk/Country",
      "race": "white"
    },
    {
      "name": "Solomon Burke",
      "rs_score": 0.0,
      "wait_time": 21,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Steely Dan",
      "rs_score": 0.0,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Steve Miller",
      "rs_score": 0.0,
      "wait_time": 23,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Stevie Nicks",
      "rs_score": 0.0,
      "wait_time": 13,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "T. Rex",
      "rs_score": 0.0,
      "wait_time": 27,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The (Young) Rascals",
      "rs_score": 0.0,
      "wait_time": 7,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Allman Brothers Band",
      "rs_score": 0.0,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Animals",
      "rs_score": 0.0,
      "wait_time": 5,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Band",
      "rs_score": 0.0,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Byrds",
      "rs_score": 0.0,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Cars",
      "rs_score": 0.0,
      "wait_time": 15,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Coasters",
      "rs_score": 0.0,
      "wait_time": 7,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Cure",
      "rs_score": 0.0,
      "wait_time": 16,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Dave Clark Five",
      "rs_score": 0.0,
      "wait_time": 20,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Doobie Brothers",
      "rs_score": 0.0,
      "wait_time": 25,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Drifters",
      "rs_score": 0.0,
      "wait_time": 10,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Everly Brothers",
      "rs_score": 0.0,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Flamingos",
      "rs_score": 0.0,
      "wait_time": 23,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Four Tops",
      "rs_score": 0.0,
      "wait_time": 9,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Go-Go's",
      "rs_score": 0.0,
      "wait_time": 15,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Grateful Dead",
      "rs_score": 0.0,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Hollies",
      "rs_score": 0.0,
      "wait_time": 22,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Impressions",
      "rs_score": 0.0,
      "wait_time": 8,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Isley Brothers",
      "rs_score": 0.0,
      "wait_time": 8,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Jackson 5",
      "rs_score": 0.0,
      "wait_time": 4,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Lovin' Spoonful",
      "rs_score": 0.0,
      "wait_time": 10,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Mamas & The Papas",
      "rs_score": 0.0,
      "wait_time": 8,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Moody Blues",
      "rs_score": 0.0,
      "wait_time": 29,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Moonglows",
      "rs_score": 0.0,
      "wait_time": 23,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The O'Jays",
      "rs_score": 0.0,
      "wait_time": 17,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Paul Butterfield Blues Band",
      "rs_score": 0.0,
      "wait_time": 25,
      "genre": "Blues/Early",
      "race": "white"
    },
    {
      "name": "The Platters",
      "rs_score": 0.0,
      "wait_time": 12,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Police",
      "rs_score": 0.0,
      "wait_time": 0,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Pretenders",
      "rs_score": 0.0,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Righteous Brothers",
      "rs_score": 0.0,
      "wait_time": 16,
      "genre": "Pop",
      "race": "white"
    },
    {
      "name": "The Ronettes",
      "rs_score": 0.0,
      "wait_time": 21,
      "genre": "Pop",
      "race": "Black"
    },
    {
      "name": "The Shirelles",
      "rs_score": 0.0,
      "wait_time": 13,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Small Faces/Faces",
      "rs_score": 0.0,
      "wait_time": 22,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Spinners",
      "rs_score": 0.0,
      "wait_time": 37,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Staple Singers",
      "rs_score": 0.0,
      "wait_time": 21,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Stooges",
      "rs_score": 0.0,
      "wait_time": 16,
      "genre": "Punk",
      "race": "white"
    },
    {
      "name": "The Supremes",
      "rs_score": 0.0,
      "wait_time": 2,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Temptations",
      "rs_score": 0.0,
      "wait_time": 3,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "The Ventures",
      "rs_score": 0.0,
      "wait_time": 24,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Yardbirds",
      "rs_score": 0.0,
      "wait_time": 4,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "The Zombies",
      "rs_score": 0.0,
      "wait_time": 30,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Todd Rundgren",
      "rs_score": 0.0,
      "wait_time": 26,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Tom Petty & The Heartbreakers",
      "rs_score": 0.0,
      "wait_time": 1,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Tom Waits",
      "rs_score": 0.0,
      "wait_time": 13,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Traffic",
      "rs_score": 0.0,
      "wait_time": 12,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "Willie Nelson",
      "rs_score": 0.0,
      "wait_time": 42,
      "genre": "Folk/Country",
      "race": "white"
    },
    {
      "name": "Wilson Pickett",
      "rs_score": 0.0,
      "wait_time": 7,
      "genre": "Soul/R&B",
      "race": "Black"
    },
    {
      "name": "Yes",
      "rs_score": 0.0,
      "wait_time": 23,
      "genre": "Classic Rock",
      "race": "white"
    },
    {
      "name": "ZZ Top",
      "rs_score": 0.0,
      "wait_time": 9,
      "genre": "Classic Rock",
      "race": "white"
    }
  ],
  "committee": {
    "wenner_tenure": {
      "committee_member": "1986-2006",
      "chairman": "2006-2019",
      "board_removed": "September 2023",
      "removal_source": "New York Times interview, September 2023"
    },
    "documented_rs_connections": [
      {
        "name": "Jann Wenner",
        "role": "Founder, Rolling Stone; Chairman, Rock Hall Foundation",
        "years": "1986-2019",
        "source": "Rock Hall Foundation public records"
      },
      {
        "name": "John Sykes",
        "role": "Chairman (post-Wenner)",
        "years": "2020-present",
        "source": "Rock Hall Foundation announcement, 2019"
      }
    ],
    "wenner_quote_2023": {
      "quote": "Wenner told the New York Times that Black and female artists did not meet his 'historical standard.'",
      "source": "New York Times, David Marchese interview, September 15, 2023",
      "context": "Interview promoting Wenner's book 'The Masters.' Wenner was asked why no women or Black artists were featured."
    },
    "wenner_quote_2022": {
      "quote": "Foreigner, Boston, Styx, and 'that whole era' had simply 'never come up' in nominating committee discussions.",
      "source": "Podcast interview, 2022 (documented in Billboard reporting)",
      "context": "Wenner explaining why certain classic rock and arena rock bands were never nominated during his committee tenure."
    },
    "note": "All claims about named individuals are sourced to documented public statements. No motives are imputed."
  },
  "metadata": {
    "source": "Rolling Stone published lists (500 Greatest Albums, 100 Greatest Artists, etc.)",
    "method": "Pearson and Spearman correlation between RS Attention Score and induction wait time",
    "causation_caveat": "This analysis documents CORRELATION between Rolling Stone editorial attention and Hall of Fame induction timing. It does NOT prove that Rolling Stone coverage CAUSED faster induction. The correlation may reflect shared aesthetic preferences rather than direct influence. The chapter states this explicitly.",
    "rs_score_method": "Weighted composite of appearances across 4 major Rolling Stone lists. Not a measure of artistic quality. A measure of editorial attention.",
    "limitation": "The full Wenner Coefficient model requires the eligible non-inducted population as controls. This preliminary analysis uses induction wait time as the outcome variable instead."
  }
};
