// One Long Impersonation -- Chapter 01: Teachers
// D3 visualization engine for the Teacher-Student Gap exhibit
// Reads from window.TEACHERS_DATA (generated by pipeline)

(function() {
  'use strict';

  var data = window.TEACHERS_DATA;
  if (!data) {
    console.error('[teachers-engine] No data found. Run pipeline first.');
    return;
  }

  var pairs = data.pairs;
  var stats = data.stats;

  // -------------------------------------------------------
  // Populate headline statistics
  // -------------------------------------------------------
  function populateStats() {
    var bwEl = document.getElementById('stat-bw-gap');
    var sameEl = document.getElementById('stat-same-gap');
    var diffEl = document.getElementById('stat-diff');
    var nEl = document.getElementById('stat-n-pairs');

    // Use teacher-waited subset stats (clearly labeled in the HTML)
    if (bwEl && stats.tw_bw_median_gap != null) bwEl.textContent = stats.tw_bw_median_gap;
    if (sameEl && stats.tw_same_race_median_gap != null) sameEl.textContent = stats.tw_same_race_median_gap;
    if (diffEl && stats.tw_raw_difference != null) diffEl.textContent = stats.tw_raw_difference;
    if (nEl) nEl.textContent = stats.total_pairs;
  }

  // -------------------------------------------------------
  // Composition to color mapping
  // -------------------------------------------------------
  function compColor(comp) {
    switch (comp) {
      case 'BW': return '#b03434';  // blood -- Black teacher, white student
      case 'BB': return '#d4a017';  // gold -- same race (Black-Black)
      case 'WW': return '#8a8aa3';  // mute -- White-White
      case 'WB': return '#5f7d56';  // moss
      default:   return 'rgba(216,207,182,0.5)'; // cream, dimmed
    }
  }

  // -------------------------------------------------------
  // Gap chart: horizontal pair visualization
  // -------------------------------------------------------
  function renderGapChart() {
    var container = document.getElementById('gap-chart');
    if (!container) return;

    // Filter to pairs where student is inducted
    var vizPairs = pairs.filter(function(p) { return p.student_inducted_year; });

    // Sort by gap descending
    vizPairs.sort(function(a, b) { return b.gap_years - a.gap_years; });

    // Dimensions -- responsive
    var isMobile = container.clientWidth < 600;
    var margin = isMobile
      ? { top: 40, right: 60, bottom: 40, left: 200 }
      : { top: 50, right: 120, bottom: 50, left: 360 };
    var rowHeight = isMobile ? 24 : 28;
    var width = Math.max(container.clientWidth, isMobile ? 360 : 700);
    var height = margin.top + vizPairs.length * rowHeight + margin.bottom;

    // Year range
    var minYear = 1985;
    var maxYear = 2028;

    // Scales
    var x = d3.scaleLinear()
      .domain([minYear, maxYear])
      .range([margin.left, width - margin.right]);

    var y = function(i) { return margin.top + i * rowHeight; };

    // Create SVG
    var svg = d3.select(container)
      .append('svg')
      .attr('width', width)
      .attr('height', height)
      .attr('viewBox', '0 0 ' + width + ' ' + height)
      .attr('role', 'img')
      .attr('aria-label', 'Teacher-Student Gap visualization showing ' + vizPairs.length +
            ' documented influence pairs with induction year gaps');

    // Background
    svg.append('rect')
      .attr('width', width)
      .attr('height', height)
      .attr('fill', '#14142b');

    // Grid lines (years)
    var gridYears = d3.range(1985, 2030, 5);
    gridYears.forEach(function(yr) {
      svg.append('line')
        .attr('x1', x(yr)).attr('x2', x(yr))
        .attr('y1', margin.top - 10).attr('y2', height - margin.bottom)
        .attr('stroke', '#2e2e55')
        .attr('stroke-width', 1);

      svg.append('text')
        .attr('x', x(yr)).attr('y', height - margin.bottom + 20)
        .attr('text-anchor', 'middle')
        .attr('fill', '#8a8aa3')
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 10)
        .text(yr);
    });

    // "NEVER" rail on the right edge
    svg.append('line')
      .attr('x1', x(maxYear - 0.5)).attr('x2', x(maxYear - 0.5))
      .attr('y1', margin.top - 10).attr('y2', height - margin.bottom)
      .attr('stroke', '#b03434')
      .attr('stroke-width', 1)
      .attr('stroke-dasharray', '4,4')
      .attr('opacity', 0.6);

    svg.append('text')
      .attr('x', x(maxYear - 0.5)).attr('y', margin.top - 16)
      .attr('text-anchor', 'middle')
      .attr('fill', '#b03434')
      .attr('font-family', '"JetBrains Mono", monospace')
      .attr('font-size', 9)
      .attr('letter-spacing', '0.15em')
      .text('NEVER');

    // Crosshair corner ticks (forensic exhibit framing)
    var tickLen = 12;
    var tickStroke = 'rgba(212,160,23,0.4)';
    // Top-left
    svg.append('line').attr('x1',4).attr('y1',4).attr('x2',4+tickLen).attr('y2',4).attr('stroke',tickStroke);
    svg.append('line').attr('x1',4).attr('y1',4).attr('x2',4).attr('y2',4+tickLen).attr('stroke',tickStroke);
    // Top-right
    svg.append('line').attr('x1',width-4).attr('y1',4).attr('x2',width-4-tickLen).attr('y2',4).attr('stroke',tickStroke);
    svg.append('line').attr('x1',width-4).attr('y1',4).attr('x2',width-4).attr('y2',4+tickLen).attr('stroke',tickStroke);
    // Bottom-left
    svg.append('line').attr('x1',4).attr('y1',height-4).attr('x2',4+tickLen).attr('y2',height-4).attr('stroke',tickStroke);
    svg.append('line').attr('x1',4).attr('y1',height-4).attr('x2',4).attr('y2',height-4-tickLen).attr('stroke',tickStroke);
    // Bottom-right
    svg.append('line').attr('x1',width-4).attr('y1',height-4).attr('x2',width-4-tickLen).attr('y2',height-4).attr('stroke',tickStroke);
    svg.append('line').attr('x1',width-4).attr('y1',height-4).attr('x2',width-4).attr('y2',height-4-tickLen).attr('stroke',tickStroke);

    // Legend
    var legendY = margin.top - 16;
    // Teacher marker
    svg.append('circle').attr('cx', margin.left).attr('cy', legendY).attr('r', 4)
      .attr('fill', 'none').attr('stroke', '#d4a017').attr('stroke-width', 2);
    svg.append('text').attr('x', margin.left + 10).attr('y', legendY + 4)
      .attr('fill', '#8a8aa3').attr('font-family', '"Inter", sans-serif').attr('font-size', 10)
      .text('Teacher inducted');
    // Student marker
    svg.append('circle').attr('cx', margin.left + 120).attr('cy', legendY).attr('r', 4)
      .attr('fill', '#efe8d6').attr('stroke', '#d4a017').attr('stroke-width', 1.5);
    svg.append('text').attr('x', margin.left + 130).attr('y', legendY + 4)
      .attr('fill', '#8a8aa3').attr('font-family', '"Inter", sans-serif').attr('font-size', 10)
      .text('Student inducted');
    // Never marker
    svg.append('circle').attr('cx', margin.left + 250).attr('cy', legendY).attr('r', 4)
      .attr('fill', 'none').attr('stroke', '#b03434').attr('stroke-width', 2);
    svg.append('text').attr('x', margin.left + 260).attr('y', legendY + 4)
      .attr('fill', '#8a8aa3').attr('font-family', '"Inter", sans-serif').attr('font-size', 10)
      .text('Teacher never inducted');

    // Render each pair
    vizPairs.forEach(function(p, i) {
      var cy = y(i) + rowHeight / 2;
      var color = compColor(p.composition);

      // Student dot position
      var studentX = x(p.student_inducted_year);

      // Teacher dot position
      var teacherX;
      if (p.teacher_never_inducted) {
        teacherX = x(maxYear - 0.5);  // At the NEVER rail
      } else if (p.teacher_inducted_year) {
        teacherX = x(p.teacher_inducted_year);
      } else {
        teacherX = x(maxYear - 0.5);
      }

      // Teacher -> Student name (left label)
      var labelText = svg.append('text')
        .attr('x', margin.left - 12)
        .attr('y', cy + 4)
        .attr('text-anchor', 'end')
        .attr('font-family', '"Inter", sans-serif')
        .attr('font-size', 11)
        .attr('font-weight', 500);
      labelText.append('tspan').attr('fill', color).text(p.teacher);
      labelText.append('tspan').attr('fill', '#8a8aa3').text(' \u2192 ');
      labelText.append('tspan').attr('fill', '#efe8d6').text(p.student);

      // Connection line
      var lineLeft = Math.min(studentX, teacherX);
      var lineRight = Math.max(studentX, teacherX);

      // Line thickness scales with gap
      var lineWidth = Math.max(1.5, Math.min(p.gap_years / 10, 4));

      svg.append('line')
        .attr('x1', lineLeft)
        .attr('x2', lineRight)
        .attr('y1', cy)
        .attr('y2', cy)
        .attr('stroke', color)
        .attr('stroke-width', lineWidth)
        .attr('opacity', 0.7);

      // Student dot (filled circle)
      svg.append('circle')
        .attr('cx', studentX)
        .attr('cy', cy)
        .attr('r', 4)
        .attr('fill', '#efe8d6')
        .attr('stroke', color)
        .attr('stroke-width', 1.5);

      // Teacher dot (hollow ring if inducted, X if never)
      if (p.teacher_never_inducted) {
        // Red hollow ring for never inducted
        svg.append('circle')
          .attr('cx', teacherX)
          .attr('cy', cy)
          .attr('r', 4)
          .attr('fill', 'none')
          .attr('stroke', '#b03434')
          .attr('stroke-width', 2);
      } else {
        // Gold ring for inducted (eventually)
        svg.append('circle')
          .attr('cx', teacherX)
          .attr('cy', cy)
          .attr('r', 4)
          .attr('fill', 'none')
          .attr('stroke', color)
          .attr('stroke-width', 2);
      }

      // Gap label (right side)
      var gapText = p.teacher_never_inducted ? 'NEVER' : p.gap_years + 'y';
      svg.append('text')
        .attr('x', width - margin.right + 16)
        .attr('y', cy + 4)
        .attr('fill', p.teacher_never_inducted ? '#b03434' : '#8a8aa3')
        .attr('font-family', '"JetBrains Mono", monospace')
        .attr('font-size', 10)
        .attr('font-weight', p.teacher_never_inducted ? 600 : 400)
        .attr('letter-spacing', '0.08em')
        .text(gapText);
    });
  }

  // -------------------------------------------------------
  // Featured cases (prosecution's witnesses)
  // -------------------------------------------------------
  function renderFeaturedCases() {
    var container = document.getElementById('featured-cases');
    if (!container) return;

    // Top cases by gap
    var featured = pairs
      .filter(function(p) { return p.gap_years >= 30 || p.teacher_never_inducted; })
      .sort(function(a, b) { return b.gap_years - a.gap_years; })
      .slice(0, 6);

    featured.forEach(function(p) {
      var card = document.createElement('div');
      card.className = 'case-card';

      var teacherYear = p.teacher_inducted_year || 'never inducted';
      var gapClass = p.teacher_never_inducted ? 'case-card__gap case-card__gap--never' : 'case-card__gap';
      var gapText = p.teacher_never_inducted ? 'Never inducted' : p.gap_years + '-year gap';

      card.innerHTML =
        '<div class="case-card__header">' +
          '<span class="case-card__names">' + p.teacher + ' &rarr; ' + p.student + '</span>' +
          '<span class="' + gapClass + '">' + gapText + '</span>' +
        '</div>' +
        '<div class="case-card__years">' +
          'Teacher: ' + teacherYear + ' / Student: ' + p.student_inducted_year +
        '</div>';

      container.appendChild(card);
    });
  }

  // -------------------------------------------------------
  // Initialize
  // -------------------------------------------------------
  function init() {
    populateStats();
    renderGapChart();
    renderFeaturedCases();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
